const dictionary = {
  // Природа и погода
  "дерево": "tree", "столб": "pole", "солнце": "sun", "луна": "moon", "звезда": "star",
  "облако": "cloud", "дождь": "rain", "снег": "snow", "гроза": "thunder", "ветер": "wind",
  "радуга": "rainbow", "гора": "mountain", "река": "river", "озеро": "lake", "море": "sea",
  "волна": "wave", "песок": "sand", "камень": "stone", "трава": "grass", "лист": "leaf",
  "цветок": "flower", "роза": "rose", "кактус": "cactus", "гриб": "mushroom", "ягода": "berry",
  
  // Животные
  "кот": "cat", "собака": "dog", "мышь": "mouse", "крыса": "rat", "кролик": "rabbit",
  "лиса": "fox", "волк": "wolf", "медведь": "bear", "олень": "deer", "лошадь": "horse",
  "корова": "cow", "свинья": "pig", "овца": "sheep", "коза": "goat", "курица": "chicken",
  "петух": "rooster", "утка": "duck", "гусь": "goose", "индюк": "turkey", "птица": "bird",
  "воробей": "sparrow", "орёл": "eagle", "сова": "owl", "голубь": "pigeon", "лебедь": "swan",
  "рыба": "fish", "дельфин": "dolphin", "кит": "whale", "акула": "shark", "осьминог": "octopus",
  "краб": "crab", "креветка": "shrimp", "бабочка": "butterfly", "пчела": "bee", "муравей": "ant",
  "паук": "spider", "божья_коровка": "ladybug", "змея": "snake", "черепаха": "turtle", "лягушка": "frog",
  
  // Еда и напитки
  "яблоко": "apple", "груша": "pear", "апельсин": "orange", "мандарин": "tangerine", "лимон": "lemon",
  "банан": "banana", "виноград": "grapes", "арбуз": "watermelon", "клубника": "strawberry", "вишня": "cherries",
  "персик": "peach", "ананас": "pineapple", "манго": "mango", "морковь": "carrot", "картофель": "potato",
  "помидор": "tomato", "огурец": "cucumber", "брокколи": "broccoli", "перец": "pepper", "кукуруза": "corn",
  "хлеб": "bread", "багет": "baguette", "булочка": "bun", "блины": "pancakes", "пицца": "pizza",
  "бургер": "burger", "хот_дог": "hotdog", "тако": "taco", "суши": "sushi", "сыр": "cheese",
  "яйцо": "egg", "бекон": "bacon", "курица_еда": "poultry_leg", "мясо": "meat", "рыба_еда": "fish_food",
  "суп": "soup", "салат": "salad", "рис": "rice", "макароны": "pasta", "торт": "cake",
  "мороженое": "ice_cream", "пончик": "doughnut", "печенье": "cookie", "шоколад": "chocolate", "конфета": "candy",
  "чай": "tea", "кофе": "coffee", "какао": "hot_chocolate", "сок": "juice", "вода": "water",
  "пиво": "beer", "вино": "wine", "коктейль": "cocktail", "молоко": "milk", "йогурт": "yogurt",
  
  // Дом и мебель
  "дом": "house", "квартира": "apartment", "комната": "room", "дверь": "door", "окно": "window",
  "стол": "table", "стул": "chair", "кресло": "armchair", "диван": "sofa", "кровать": "bed",
  "шкаф": "wardrobe", "комод": "drawer", "полка": "shelf", "ковёр": "carpet", "лампа": "lamp",
  "люстра": "chandelier", "зеркало": "mirror", "картина": "painting", "книга": "book", "книги": "books",
  "газета": "newspaper", "журнал": "magazine", "компьютер": "computer", "ноутбук": "laptop", "телефон": "phone",
  "телевизор": "tv", "часы": "clock", "будильник": "alarm_clock", "холодильник": "fridge", "микроволновка": "microwave",
  "плита": "stove", "чайник": "kettle", "тостер": "toaster", "кофеварка": "coffee_maker", "пылесос": "vacuum",
  "веник": "broom", "ведро": "bucket", "стиральная_машина": "washer", "утюг": "iron", "вешалка": "coat_hanger",
  
  // Одежда и аксессуары
  "футболка": "t_shirt", "рубашка": "shirt", "джинсы": "jeans", "брюки": "trousers", "юбка": "skirt",
  "платье": "dress", "пальто": "coat", "куртка": "jacket", "шапка": "hat", "кепка": "cap",
  "панама": "sunhat", "шарф": "scarf", "перчатки": "gloves", "обувь": "shoes", "ботинки": "boots",
  "кроссовки": "sneakers", "тапки": "slippers", "носки": "socks", "часы_наручные": "wristwatch", "очки": "glasses",
  "солнечные_очки": "sunglasses", "рюкзак": "backpack", "сумка": "bag", "кошелёк": "wallet", "ремень": "belt",
  "галстук": "necktie", "шляпа": "top_hat", "корона": "crown", "кольцо": "ring", "серьги": "earrings",
  
  // Транспорт
  "машина": "car", "такси": "taxi", "автобус": "bus", "троллейбус": "trolleybus", "трамвай": "tram",
  "поезд": "train", "метро": "metro", "электропоезд": "light_rail", "трамвай": "tram", "мотоцикл": "motorcycle",
  "велосипед": "bicycle", "самокат": "scooter", "самолёт": "airplane", "вертолёт": "helicopter", "корабль": "ship",
  "лодка": "boat", "яхта": "yacht", "подводная_лодка": "submarine", "ракета": "rocket", "космический_корабль": "spaceship",
  "грузовик": "truck", "фургон": "van", "пожарная_машина": "fire_engine", "скорая": "ambulance", "полицейская_машина": "police_car",
  
  // Профессии и люди
  "человек": "person", "люди": "people", "ребёнок": "child", "мужчина": "man", "женщина": "woman",
  "полицейский": "police", "врач": "doctor", "учитель": "teacher", "повар": "cook", "фермер": "farmer",
  "строитель": "construction_worker", "механик": "mechanic", "художник": "artist", "музыкант": "musician", "танцор": "dancer",
  "спортсмен": "athlete", "плавец": "swimmer", "певец": "singer", "учёный": "scientist", "инженер": "engineer",
  "пилот": "pilot", "водитель": "driver", "программист": "technologist", "юрист": "judge", "продавец": "salesperson",
  
  // Эмоции и лицо
  "улыбка": "smile", "смех": "laugh", "грусть": "sad", "плач": "cry", "гнев": "angry",
  "удивление": "surprised", "страх": "fear", "любовь": "love", "сердце": "heart", "поцелуй": "kiss",
  "глаза": "eyes", "нос": "nose", "рот": "mouth", "голова": "head", "рука": "hand",
  "нога": "foot", "палец": "finger", "волосы": "hair", "ухо": "ear", "мозг": "brain",
  "глаз": "eye", "губы": "lips", "зуб": "tooth", "язык": "tongue", "нога_стопа": "foot",
  
  // Действия и жесты
  "бежать": "running", "ходить": "walking", "стоять": "standing", "сидеть": "sitting", "лежать": "lying",
  "прыгать": "jumping", "плавать": "swimming", "летать": "flying", "ехать": "driving", "работать": "working",
  "учить": "studying", "читать": "reading", "писать": "writing", "рисовать": "drawing", "играть": "playing",
  "спать": "sleeping", "есть": "eating", "пить": "drinking", "готовить": "cooking", "мыть": "washing",
  "чистить": "cleaning", "танцевать": "dancing", "петь": "singing", "кричать": "shouting", "молчать": "silent",
  "аплодировать": "clapping", "пожать_плечами": "shrug", "махать": "waving", "указывать": "pointing", "обнимать": "hugging",
  
  // Спорт и хобби
  "футбол": "soccer", "баскетбол": "basketball", "волейбол": "volleyball", "теннис": "tennis", "хоккей": "hockey",
  "гантели": "weight_lifting", "бег": "running_sport", "велоспорт": "cycling", "йога": "yoga", "карате": "karate",
  "шахматы": "chess", "покер": "poker", "музыка": "music", "гитара": "guitar", "пианино": "piano",
  "барабан": "drum", "скрипка": "violin", "труба": "trumpet", "фотоаппарат": "camera", "видеокамера": "video_camera",
  
  // Техника и инструменты
  "компьютер": "computer", "клавиатура": "keyboard", "мышь_комп": "mouse_computer", "экран": "screen", "принтер": "printer",
  "телефон": "phone", "планшет": "tablet", "часы": "watch", "наушники": "headphones", "микрофон": "microphone",
  "динамик": "speaker", "флешка": "usb", "лампочка": "light_bulb", "батарейка": "battery", "розетка": "electric_plug",
  "молоток": "hammer", "отвёртка": "screwdriver", "гаечный_ключ": "wrench", "пила": "saw", "дрель": "drill",
  
  // Здания и места
  "школа": "school", "университет": "university", "больница": "hospital", "полиция": "police_station", "пожарная_часть": "fire_station",
  "почта": "post_office", "банк": "bank", "магазин": "shop", "супермаркет": "supermarket", "кафе": "cafe",
  "ресторан": "restaurant", "гостиница": "hotel", "церковь": "church", "мечеть": "mosque", "синагога": "synagogue",
  "стадион": "stadium", "парк": "park", "лес": "forest", "пляж": "beach", "ферма": "farm",
  
  // Городские объекты
  "знак": "sign", "светофор": "traffic_light", "остановка": "bus_stop", "мост": "bridge", "фонтан": "fountain",
  "памятник": "statue", "скамейка": "bench", "мусорка": "wastebasket", "туалет": "toilet", "фонтан_питьевой": "drinking_fountain",
  "лифт": "elevator", "эскалатор": "escalator", "лестница": "stairs", "дверь_выход": "door_exit",
  
  // Времена и календарь
  "время": "time", "часы_настенные": "clock", "календарь": "calendar", "день": "day", "ночь": "night",
  "утро": "morning", "вечер": "evening", "понедельник": "monday", "вторник": "tuesday", "среда": "wednesday",
  "четверг": "thursday", "пятница": "friday", "суббота": "saturday", "воскресенье": "sunday", "январь": "january",
  "февраль": "february", "март": "march", "апрель": "april", "май": "may", "июнь": "june",
  "июль": "july", "август": "august", "сентябрь": "september", "октябрь": "october", "ноябрь": "november",
  "декабрь": "december", "праздник": "party", "день_рождения": "birthday",
  
  // Символы и техногенные
  "замок": "lock", "ключ": "key", "скрепка": "paperclip", "ножницы": "scissors", "ручка": "pen",
  "карандаш": "pencil", "ластик": "eraser", "линейка": "ruler", "книга": "book", "дневник": "notebook",
  "конверт": "envelope", "почтовый_ящик": "mailbox", "флаг": "flag", "воздушный_шар": "balloon", "подарок": "gift",
  "свеча": "candle", "бомба": "bomb", "нож": "knife", "вилка": "fork", "ложка": "spoon",
  "тарелка": "plate", "чашка": "cup", "кружка": "mug", "стакан": "glass",
  
  // Абстрактные (имеющие эмодзи)
  "секрет": "secret", "идея": "idea", "вопрос": "question", "восклицание": "exclamation", "мир": "peace",
  "здоровье": "health", "энергия": "energy", "магия": "magic", "зомби": "zombie", "привидение": "ghost",
  "инопланетянин": "alien", "робот": "robot"
};

// Карта английских ключей → эмодзи (все ключи из dictionary)
const emojiMap = {
  "tree": "🌳", "pole": "🏗️", "sun": "☀️", "moon": "🌙", "star": "⭐",
  "cloud": "☁️", "rain": "🌧️", "snow": "❄️", "thunder": "⛈️", "wind": "💨",
  "rainbow": "🌈", "mountain": "⛰️", "river": "🏞️", "lake": "🏞️", "sea": "🌊",
  "wave": "🌊", "sand": "🏝️", "stone": "🪨", "grass": "🌿", "leaf": "🍃",
  "flower": "🌸", "rose": "🌹", "cactus": "🌵", "mushroom": "🍄", "berry": "🫐",
  "cat": "🐱", "dog": "🐶", "mouse": "🐭", "rat": "🐀", "rabbit": "🐰",
  "fox": "🦊", "wolf": "🐺", "bear": "🐻", "deer": "🦌", "horse": "🐴",
  "cow": "🐮", "pig": "🐷", "sheep": "🐑", "goat": "🐐", "chicken": "🐔",
  "rooster": "🐓", "duck": "🦆", "goose": "🦢", "turkey": "🦃", "bird": "🐦",
  "sparrow": "🐧", "eagle": "🦅", "owl": "🦉", "pigeon": "🕊️", "swan": "🦢",
  "fish": "🐟", "dolphin": "🐬", "whale": "🐳", "shark": "🦈", "octopus": "🐙",
  "crab": "🦀", "shrimp": "🦐", "butterfly": "🦋", "bee": "🐝", "ant": "🐜",
  "spider": "🕷️", "ladybug": "🐞", "snake": "🐍", "turtle": "🐢", "frog": "🐸",
  "apple": "🍎", "pear": "🍐", "orange": "🍊", "tangerine": "🍊", "lemon": "🍋",
  "banana": "🍌", "grapes": "🍇", "watermelon": "🍉", "strawberry": "🍓", "cherries": "🍒",
  "peach": "🍑", "pineapple": "🍍", "mango": "🥭", "carrot": "🥕", "potato": "🥔",
  "tomato": "🍅", "cucumber": "🥒", "broccoli": "🥦", "pepper": "🫑", "corn": "🌽",
  "bread": "🍞", "baguette": "🥖", "bun": "🍔", "pancakes": "🥞", "pizza": "🍕",
  "burger": "🍔", "hotdog": "🌭", "taco": "🌮", "sushi": "🍣", "cheese": "🧀",
  "egg": "🥚", "bacon": "🥓", "poultry_leg": "🍗", "meat": "🥩", "fish_food": "🍥",
  "soup": "🥣", "salad": "🥗", "rice": "🍚", "pasta": "🍝", "cake": "🍰",
  "ice_cream": "🍦", "doughnut": "🍩", "cookie": "🍪", "chocolate": "🍫", "candy": "🍬",
  "tea": "🍵", "coffee": "☕", "hot_chocolate": "☕", "juice": "🧃", "water": "💧",
  "beer": "🍺", "wine": "🍷", "cocktail": "🍹", "milk": "🥛", "yogurt": "🥛",
  "house": "🏠", "apartment": "🏢", "room": "🚪", "door": "🚪", "window": "🪟",
  "table": "🪑", "chair": "🪑", "armchair": "🛋️", "sofa": "🛋️", "bed": "🛏️",
  "wardrobe": "🚪", "drawer": "🗄️", "shelf": "📚", "carpet": "🧶", "lamp": "💡",
  "chandelier": "💡", "mirror": "🪞", "painting": "🖼️", "book": "📖", "books": "📚",
  "newspaper": "📰", "magazine": "📰", "computer": "💻", "laptop": "💻", "phone": "📱",
  "tv": "📺", "clock": "🕰️", "alarm_clock": "⏰", "fridge": "🧊", "microwave": "🔥",
  "stove": "🍳", "kettle": "🫖", "toaster": "🍞", "coffee_maker": "☕", "vacuum": "🧹",
  "broom": "🧹", "bucket": "🪣", "washer": "🧼", "iron": "🧺", "coat_hanger": "🧥",
  "t_shirt": "👕", "shirt": "👔", "jeans": "👖", "trousers": "👖", "skirt": "👗",
  "dress": "👗", "coat": "🧥", "jacket": "🧥", "hat": "🧢", "cap": "🧢",
  "sunhat": "👒", "scarf": "🧣", "gloves": "🧤", "shoes": "👟", "boots": "👢",
  "sneakers": "👟", "slippers": "🩴", "socks": "🧦", "wristwatch": "⌚", "glasses": "👓",
  "sunglasses": "🕶️", "backpack": "🎒", "bag": "👜", "wallet": "👛", "belt": "⛓️",
  "necktie": "👔", "top_hat": "🎩", "crown": "👑", "ring": "💍", "earrings": "💎",
  "car": "🚗", "taxi": "🚕", "bus": "🚌", "trolleybus": "🚎", "tram": "🚋",
  "train": "🚆", "metro": "🚇", "light_rail": "🚈", "motorcycle": "🏍️", "bicycle": "🚲",
  "scooter": "🛴", "airplane": "✈️", "helicopter": "🚁", "ship": "🚢", "boat": "⛵",
  "yacht": "🛥️", "submarine": "🛸", "rocket": "🚀", "spaceship": "🛸", "truck": "🚚",
  "van": "🚐", "fire_engine": "🚒", "ambulance": "🚑", "police_car": "🚓",
  "person": "🧑", "people": "👥", "child": "🧒", "man": "👨", "woman": "👩",
  "police": "👮", "doctor": "👩‍⚕️", "teacher": "👩‍🏫", "cook": "👩‍🍳", "farmer": "👩‍🌾",
  "construction_worker": "👷", "mechanic": "🔧", "artist": "🎨", "musician": "🎵", "dancer": "💃",
  "athlete": "🏋️", "swimmer": "🏊", "singer": "🎤", "scientist": "🧑‍🔬", "engineer": "🧑‍💻",
  "pilot": "👨‍✈️", "driver": "🧑‍✈️", "technologist": "🧑‍💻", "judge": "⚖️", "salesperson": "🧑‍💼",
  "smile": "😊", "laugh": "😆", "sad": "😢", "cry": "😭", "angry": "😠",
  "surprised": "😲", "fear": "😨", "love": "🥰", "heart": "❤️", "kiss": "😘",
  "eyes": "👀", "nose": "👃", "mouth": "👄", "head": "🗣️", "hand": "✋",
  "foot": "🦶", "finger": "☝️", "hair": "💇", "ear": "👂", "brain": "🧠",
  "eye": "👁️", "lips": "👄", "tooth": "🦷", "tongue": "👅", "running": "🏃",
  "walking": "🚶", "standing": "🧍", "sitting": "🧎", "lying": "🛌", "jumping": "🦘",
  "swimming": "🏊", "flying": "🕊️", "driving": "🚗", "working": "💼", "studying": "📚",
  "reading": "📖", "writing": "✍️", "drawing": "🎨", "playing": "🎮", "sleeping": "😴",
  "eating": "🍽️", "drinking": "🥤", "cooking": "🍳", "washing": "🧼", "cleaning": "🧹",
  "dancing": "💃", "singing": "🎤", "shouting": "📢", "silent": "🤫", "clapping": "👏",
  "shrug": "🤷", "waving": "👋", "pointing": "👉", "hugging": "🤗", "soccer": "⚽",
  "basketball": "🏀", "volleyball": "🏐", "tennis": "🎾", "hockey": "🏒", "weight_lifting": "🏋️",
  "running_sport": "🏃‍♂️", "cycling": "🚴", "yoga": "🧘", "karate": "🥋", "chess": "♟️",
  "poker": "🃏", "music": "🎵", "guitar": "🎸", "piano": "🎹", "drum": "🥁",
  "violin": "🎻", "trumpet": "🎺", "camera": "📷", "video_camera": "🎥", "keyboard": "⌨️",
  "mouse_computer": "🖱️", "screen": "🖥️", "printer": "🖨️", "tablet": "📱", "watch": "⌚",
  "headphones": "🎧", "microphone": "🎤", "speaker": "🔊", "usb": "🔌", "light_bulb": "💡",
  "battery": "🔋", "electric_plug": "🔌", "hammer": "🔨", "screwdriver": "🪛", "wrench": "🔧",
  "saw": "🪚", "drill": "🪛", "school": "🏫", "university": "🏛️", "hospital": "🏥",
  "police_station": "🏢", "fire_station": "🚒", "post_office": "🏤", "bank": "🏦", "shop": "🏪",
  "supermarket": "🛒", "cafe": "☕", "restaurant": "🍽️", "hotel": "🏨", "church": "⛪",
  "mosque": "🕌", "synagogue": "🕍", "stadium": "🏟️", "park": "🌳", "forest": "🌲",
  "beach": "🏖️", "farm": "🚜", "sign": "🪧", "traffic_light": "🚥", "bus_stop": "🚏",
  "bridge": "🌉", "fountain": "⛲", "statue": "🗽", "bench": "🪑", "wastebasket": "🗑️",
  "toilet": "🚽", "drinking_fountain": "🚰", "elevator": "🛗", "escalator": "🛝", "stairs": "🪜",
  "door_exit": "🚪", "time": "⏱️", "calendar": "📅", "day": "☀️", "night": "🌙",
  "morning": "🌅", "evening": "🌇", "monday": "📅", "tuesday": "📅", "wednesday": "📅",
  "thursday": "📅", "friday": "📅", "saturday": "📅", "sunday": "📅", "january": "📅",
  "february": "📅", "march": "📅", "april": "📅", "may": "📅", "june": "📅",
  "july": "📅", "august": "📅", "september": "📅", "october": "📅", "november": "📅",
  "december": "📅", "party": "🎉", "birthday": "🎂", "lock": "🔒", "key": "🔑",
  "paperclip": "📎", "scissors": "✂️", "pen": "🖊️", "pencil": "✏️", "eraser": "🧽",
  "ruler": "📏", "notebook": "📓", "envelope": "✉️", "mailbox": "📬", "flag": "🏁",
  "balloon": "🎈", "gift": "🎁", "candle": "🕯️", "bomb": "💣", "knife": "🔪",
  "fork": "🍴", "spoon": "🥄", "plate": "🍽️", "cup": "🥤", "mug": "☕",
  "glass": "🥛", "secret": "🤫", "idea": "💡", "question": "❓", "exclamation": "❗",
  "peace": "☮️", "health": "❤️", "energy": "⚡", "magic": "✨", "zombie": "🧟",
  "ghost": "👻", "alien": "👽", "robot": "🤖"
};
