const dictionary = {
  // Animals
  "кот": { en: "cat", es: "gato" },
  "собака": { en: "dog", es: "perro" },
  "мышь": { en: "mouse", es: "ratón" },
  "крыса": { en: "rat", es: "rata" },
  "хомяк": { en: "hamster", es: "hámster" },
  "кролик": { en: "rabbit", es: "conejo" },
  "лиса": { en: "fox", es: "zorro" },
  "волк": { en: "wolf", es: "lobo" },
  "медведь": { en: "bear", es: "oso" },
  "тигр": { en: "tiger", es: "tigre" },
  "лев": { en: "lion", es: "león" },
  "пантера": { en: "panther", es: "pantera" },
  "леопард": { en: "leopard", es: "leopardo" },
  "гепард": { en: "cheetah", es: "guepardo" },
  "слон": { en: "elephant", es: "elefante" },
  "жираф": { en: "giraffe", es: "jirafa" },
  "зебра": { en: "zebra", es: "cebra" },
  "лошадь": { en: "horse", es: "caballo" },
  "пони": { en: "pony", es: "poni" },
  "осёл": { en: "donkey", es: "burro" },
  "корова": { en: "cow", es: "vaca" },
  "бык": { en: "bull", es: "toro" },
  "свинья": { en: "pig", es: "cerdo" },
  "кабан": { en: "boar", es: "jabalí" },
  "овца": { en: "sheep", es: "oveja" },
  "баран": { en: "ram", es: "carnero" },
  "коза": { en: "goat", es: "cabra" },
  "олень": { en: "deer", es: "ciervo" },
  "лось": { en: "moose", es: "alce" },
  "антилопа": { en: "antelope", es: "antílope" },
  "буйвол": { en: "buffalo", es: "búfalo" },
  "бегемот": { en: "hippo", es: "hipopótamo" },
  "носорог": { en: "rhino", es: "rinoceronte" },
  "обезьяна": { en: "monkey", es: "mono" },
  "горилла": { en: "gorilla", es: "gorila" },
  "шимпанзе": { en: "chimpanzee", es: "chimpancé" },
  "ленивец": { en: "sloth", es: "perezoso" },
  "коала": { en: "koala", es: "koala" },
  "кенгуру": { en: "kangaroo", es: "canguro" },
  "панда": { en: "panda", es: "panda" },
  "енот": { en: "raccoon", es: "mapache" },
  "барсук": { en: "badger", es: "tejón" },
  "бобр": { en: "beaver", es: "castor" },
  "выдра": { en: "otter", es: "nutria" },
  "белка": { en: "squirrel", es: "ardilla" },
  "ёж": { en: "hedgehog", es: "erizo" },
  "крот": { en: "mole", es: "topo" },
  "летучая мышь": { en: "bat", es: "murciélago" },
  "верблюд": { en: "camel", es: "camello" },
  "лама": { en: "llama", es: "llama" },
  "альпака": { en: "alpaca", es: "alpaca" },
  "курица": { en: "chicken", es: "pollo" },
  "петух": { en: "rooster", es: "gallo" },
  "утка": { en: "duck", es: "pato" },
  "гусь": { en: "goose", es: "ganso" },
  "индюк": { en: "turkey", es: "pavo" },
  "лебедь": { en: "swan", es: "cisne" },
  "павлин": { en: "peacock", es: "pavo real" },
  "фламинго": { en: "flamingo", es: "flamenco" },
  "пингвин": { en: "penguin", es: "pingüino" },
  "страус": { en: "ostrich", es: "avestruz" },
  "воробей": { en: "sparrow", es: "gorrión" },
  "голубь": { en: "pigeon", es: "paloma" },
  "ворона": { en: "crow", es: "cuervo" },
  "сорока": { en: "magpie", es: "urraca" },
  "сова": { en: "owl", es: "búho" },
  "орёл": { en: "eagle", es: "águila" },
  "ястреб": { en: "hawk", es: "halcón" },
  "сокол": { en: "falcon", es: "halcón" },
  "попугай": { en: "parrot", es: "loro" },
  "канарейка": { en: "canary", es: "canario" },
  "колибри": { en: "hummingbird", es: "colibrí" },
  "чайка": { en: "seagull", es: "gaviota" },
  "журавль": { en: "crane", es: "grulla" },
  "аист": { en: "stork", es: "cigüeña" },
  "рыба": { en: "fish", es: "pez" },
  "акула": { en: "shark", es: "tiburón" },
  "кит": { en: "whale", es: "ballena" },
  "дельфин": { en: "dolphin", es: "delfín" },
  "осьминог": { en: "octopus", es: "pulpo" },
  "кальмар": { en: "squid", es: "calamar" },
  "краб": { en: "crab", es: "cangrejo" },
  "омар": { en: "lobster", es: "langosta" },
  "креветка": { en: "shrimp", es: "camarón" },
  "морская звезда": { en: "starfish", es: "estrella de mar" },
  "медуза": { en: "jellyfish", es: "medusa" },
  "морской конёк": { en: "seahorse", es: "caballito de mar" },
  "угорь": { en: "eel", es: "anguila" },
  "скат": { en: "ray", es: "raya" },
  "черепаха": { en: "turtle", es: "tortuga" },
  "крокодил": { en: "crocodile", es: "cocodrilo" },
  "аллигатор": { en: "alligator", es: "caimán" },
  "змея": { en: "snake", es: "serpiente" },
  "питон": { en: "python", es: "pitón" },
  "ящерица": { en: "lizard", es: "lagarto" },
  "хамелеон": { en: "chameleon", es: "camaleón" },
  "игуана": { en: "iguana", es: "iguana" },
  "лягушка": { en: "frog", es: "rana" },
  "жаба": { en: "toad", es: "sapo" },
  "саламандра": { en: "salamander", es: "salamandra" },
  "бабочка": { en: "butterfly", es: "mariposa" },
  "пчела": { en: "bee", es: "abeja" },
  "оса": { en: "wasp", es: "avispa" },
  "шмель": { en: "bumblebee", es: "abejorro" },
  "муравей": { en: "ant", es: "hormiga" },
  "паук": { en: "spider", es: "araña" },
  "скорпион": { en: "scorpion", es: "escorpión" },
  "таракан": { en: "cockroach", es: "cucaracha" },
  "муха": { en: "fly", es: "mosca" },
  "комар": { en: "mosquito", es: "mosquito" },
  "стрекоза": { en: "dragonfly", es: "libélula" },
  "кузнечик": { en: "grasshopper", es: "saltamontes" },
  "сверчок": { en: "cricket", es: "grillo" },
  "жук": { en: "beetle", es: "escarabajo" },
  "божья коровка": { en: "ladybug", es: "mariquita" },
  "гусеница": { en: "caterpillar", es: "oruga" },
  "улитка": { en: "snail", es: "caracol" },
  "слизень": { en: "slug", es: "babosa" },
  "червь": { en: "worm", es: "gusano" },

  // Professions
  "врач": { en: "doctor", es: "médico" },
  "учитель": { en: "teacher", es: "profesor" },
  "пожарный": { en: "firefighter", es: "bombero" },
  "полицейский": { en: "police officer", es: "policía" },
  "повар": { en: "chef", es: "cocinero" },
  "художник": { en: "artist", es: "artista" },
  "музыкант": { en: "musician", es: "músico" },
  "пилот": { en: "pilot", es: "piloto" },
  "программист": { en: "programmer", es: "programador" },
  "учёный": { en: "scientist", es: "científico" },
  "строитель": { en: "construction worker", es: "obrero de la construcción" },
  "инженер": { en: "engineer", es: "ingeniero" },
  "водитель": { en: "driver", es: "conductor" },
  "медсестра": { en: "nurse", es: "enfermero" },
  "аптекарь": { en: "pharmacist", es: "farmacéutico" },
  "ветеринар": { en: "veterinarian", es: "veterinario" },
  "стоматолог": { en: "dentist", es: "dentista" },
  "психолог": { en: "psychologist", es: "psicólogo" },
  "юрист": { en: "lawyer", es: "abogado" },
  "судья": { en: "judge", es: "juez" },
  "журналист": { en: "journalist", es: "periodista" },
  "писатель": { en: "writer", es: "escritor" },
  "актёр": { en: "actor", es: "actor" },
  "режиссёр": { en: "director", es: "director" },
  "фотограф": { en: "photographer", es: "fotógrafo" },
  "дизайнер": { en: "designer", es: "diseñador" },
  "архитектор": { en: "architect", es: "arquitecto" },
  "бухгалтер": { en: "accountant", es: "contable" },
  "переводчик": { en: "translator", es: "traductor" },
  "дипломат": { en: "diplomat", es: "diplomático" },
  "спасатель": { en: "lifeguard", es: "salvavidas" },
  "детектив": { en: "detective", es: "detective" },
  "хирург": { en: "surgeon", es: "cirujano" },
  "фармацевт": { en: "pharmacist", es: "farmacéutico" },
  "электрик": { en: "electrician", es: "electricista" },
  "сантехник": { en: "plumber", es: "fontanero" },
  "механик": { en: "mechanic", es: "mecánico" },
  "сварщик": { en: "welder", es: "soldador" },
  "фермер": { en: "farmer", es: "granjero" },
  "пекарь": { en: "baker", es: "panadero" },
  "кондитер": { en: "pastry chef", es: "pastelero" },
  "мясник": { en: "butcher", es: "carnicero" },
  "парикмахер": { en: "hairdresser", es: "peluquero" },
  "стилист": { en: "stylist", es: "estilista" },
  "визажист": { en: "makeup artist", es: "maquillador" },
  "тренер": { en: "coach", es: "entrenador" },
  "спортсмен": { en: "athlete", es: "atleta" },
  "бариста": { en: "barista", es: "barista" },
  "официант": { en: "waiter", es: "camarero" },
  "стюардесса": { en: "flight attendant", es: "auxiliar de vuelo" },
  "секретарь": { en: "secretary", es: "secretario" },
  "менеджер": { en: "manager", es: "gerente" },
  "предприниматель": { en: "entrepreneur", es: "emprendedor" },
  "военный": { en: "military officer", es: "oficial militar" },

  // Nature & Weather
  "солнце": { en: "sun", es: "sol" },
  "дождь": { en: "rain", es: "lluvia" },
  "снег": { en: "snow", es: "nieve" },
  "ветер": { en: "wind", es: "viento" },
  "облако": { en: "cloud", es: "nube" },
  "гроза": { en: "thunderstorm", es: "tormenta eléctrica" },
  "молния": { en: "lightning", es: "relámpago" },
  "гром": { en: "thunder", es: "trueno" },
  "град": { en: "hail", es: "granizo" },
  "туман": { en: "fog", es: "niebla" },
  "радуга": { en: "rainbow", es: "arco iris" },
  "ураган": { en: "hurricane", es: "huracán" },
  "торнадо": { en: "tornado", es: "tornado" },
  "засуха": { en: "drought", es: "sequía" },
  "наводнение": { en: "flood", es: "inundación" },
  "жара": { en: "heat", es: "calor" },
  "мороз": { en: "frost", es: "helada" },
  "лёд": { en: "ice", es: "hielo" },
  "небо": { en: "sky", es: "cielo" },
  "звезда": { en: "star", es: "estrella" },
  "луна": { en: "moon", es: "luna" },
  "планета": { en: "planet", es: "planeta" },
  "земля": { en: "earth", es: "tierra" },
  "воздух": { en: "air", es: "aire" },
  "вода": { en: "water", es: "agua" },
  "огонь": { en: "fire", es: "fuego" },
  "лес": { en: "forest", es: "bosque" },
  "дерево": { en: "tree", es: "árbol" },
  "лист": { en: "leaf", es: "hoja" },
  "цветок": { en: "flower", es: "flor" },
  "трава": { en: "grass", es: "hierba" },
  "куст": { en: "bush", es: "arbusto" },
  "гора": { en: "mountain", es: "montaña" },
  "холм": { en: "hill", es: "colina" },
  "долина": { en: "valley", es: "valle" },
  "поле": { en: "field", es: "campo" },
  "луг": { en: "meadow", es: "prado" },
  "река": { en: "river", es: "río" },
  "озеро": { en: "lake", es: "lago" },
  "море": { en: "sea", es: "mar" },
  "океан": { en: "ocean", es: "océano" },
  "остров": { en: "island", es: "isla" },
  "полуостров": { en: "peninsula", es: "península" },
  "пляж": { en: "beach", es: "playa" },
  "пустыня": { en: "desert", es: "desierto" },
  "водопад": { en: "waterfall", es: "cascada" },
  "вулкан": { en: "volcano", es: "volcán" },
  "айсберг": { en: "iceberg", es: "iceberg" },
  "пещера": { en: "cave", es: "cueva" },
  "скала": { en: "rock", es: "roca" },
  "камень": { en: "stone", es: "piedra" },
  "песок": { en: "sand", es: "arena" },
  "грязь": { en: "mud", es: "barro" },
  "почва": { en: "soil", es: "suelo" },
  "роса": { en: "dew", es: "rocío" },
  "сосулька": { en: "icicle", es: "carámbano" },

  // Transport
  "машина": { en: "car", es: "coche" },
  "автомобиль": { en: "automobile", es: "automóvil" },
  "автобус": { en: "bus", es: "autobús" },
  "троллейбус": { en: "trolleybus", es: "trolebús" },
  "трамвай": { en: "tram", es: "tranvía" },
  "поезд": { en: "train", es: "tren" },
  "электричка": { en: "commuter train", es: "tren de cercanías" },
  "метро": { en: "subway", es: "metro" },
  "самолёт": { en: "airplane", es: "avión" },
  "вертолёт": { en: "helicopter", es: "helicóptero" },
  "корабль": { en: "ship", es: "barco" },
  "лодка": { en: "boat", es: "bote" },
  "катер": { en: "motorboat", es: "lancha motora" },
  "яхта": { en: "yacht", es: "yate" },
  "паром": { en: "ferry", es: "ferry" },
  "подводная лодка": { en: "submarine", es: "submarino" },
  "велосипед": { en: "bicycle", es: "bicicleta" },
  "мотоцикл": { en: "motorcycle", es: "motocicleta" },
  "мопед": { en: "moped", es: "ciclomotor" },
  "скутер": { en: "scooter", es: "scooter" },
  "самокат": { en: "kick scooter", es: "patinete" },
  "такси": { en: "taxi", es: "taxi" },
  "грузовик": { en: "truck", es: "camión" },
  "фура": { en: "semi-truck", es: "trailer" },
  "самосвал": { en: "dump truck", es: "volquete" },
  "экскаватор": { en: "excavator", es: "excavadora" },
  "бульдозер": { en: "bulldozer", es: "bulldozer" },
  "трактор": { en: "tractor", es: "tractor" },
  "скорая помощь": { en: "ambulance", es: "ambulancia" },
  "пожарная машина": { en: "fire truck", es: "camión de bomberos" },
  "полицейская машина": { en: "police car", es: "coche de policía" },
  "эвакуатор": { en: "tow truck", es: "grúa" },
  "бензовоз": { en: "fuel truck", es: "camión cisterna" },
  "микроавтобус": { en: "minibus", es: "microbús" },
  "внедорожник": { en: "SUV", es: "todoterreno" },
  "кабриолет": { en: "convertible", es: "descapotable" },
  "лимузин": { en: "limousine", es: "limusina" },
  "карт": { en: "go-kart", es: "kart" },
  "квадроцикл": { en: "ATV", es: "cuatrimoto" },
  "снегоход": { en: "snowmobile", es: "motonieve" },
  "дирижабль": { en: "airship", es: "dirigible" },
  "воздушный шар": { en: "hot air balloon", es: "globo aerostático" },
  "дельтаплан": { en: "hang glider", es: "ala delta" },
  "канатная дорога": { en: "cable car", es: "teleférico" },
  "фуникулёр": { en: "funicular", es: "funicular" },
  "танк": { en: "tank", es: "tanque" },
  "бронетранспортёр": { en: "armored vehicle", es: "vehículo blindado" },
  "ракета": { en: "rocket", es: "cohete" },
  "космический корабль": { en: "spaceship", es: "nave espacial" },
  "спутник": { en: "satellite", es: "satélite" },
  "байдарка": { en: "kayak", es: "kayak" },
  "каноэ": { en: "canoe", es: "canoa" },
  "катамаран": { en: "catamaran", es: "catamarán" },
  "гидроцикл": { en: "jet ski", es: "moto acuática" },

  // Clothes & Accessories
  "одежда": { en: "clothes", es: "ropa" },
  "футболка": { en: "t-shirt", es: "camiseta" },
  "рубашка": { en: "shirt", es: "camisa" },
  "блузка": { en: "blouse", es: "blusa" },
  "свитер": { en: "sweater", es: "suéter" },
  "кофта": { en: "hoodie", es: "sudadera" },
  "куртка": { en: "jacket", es: "chaqueta" },
  "пальто": { en: "coat", es: "abrigo" },
  "плащ": { en: "raincoat", es: "impermeable" },
  "шуба": { en: "fur coat", es: "abrigo de piel" },
  "жилет": { en: "vest", es: "chaleco" },
  "пиджак": { en: "blazer", es: "blazer" },
  "костюм": { en: "suit", es: "traje" },
  "джинсы": { en: "jeans", es: "vaqueros" },
  "брюки": { en: "trousers", es: "pantalones" },
  "шорты": { en: "shorts", es: "pantalones cortos" },
  "штаны": { en: "pants", es: "pantalones" },
  "юбка": { en: "skirt", es: "falda" },
  "платье": { en: "dress", es: "vestido" },
  "сарафан": { en: "sundress", es: "vestido de verano" },
  "комбинезон": { en: "overalls", es: "mono" },
  "трусы": { en: "underwear", es: "ropa interior" },
  "бюстгальтер": { en: "bra", es: "sujetador" },
  "носки": { en: "socks", es: "calcetines" },
  "гольфы": { en: "knee socks", es: "calcetines altos" },
  "колготки": { en: "tights", es: "panty" },
  "пижама": { en: "pajamas", es: "pijama" },
  "халат": { en: "robe", es: "bata" },
  "купальник": { en: "swimsuit", es: "traje de baño" },
  "плавки": { en: "swim trunks", es: "bañador" },
  "шапка": { en: "hat", es: "gorro" },
  "кепка": { en: "cap", es: "gorra" },
  "шляпа": { en: "hat", es: "sombrero" },
  "берет": { en: "beret", es: "boina" },
  "шарф": { en: "scarf", es: "bufanda" },
  "перчатки": { en: "gloves", es: "guantes" },
  "варежки": { en: "mittens", es: "mitones" },
  "ремень": { en: "belt", es: "cinturón" },
  "галстук": { en: "tie", es: "corbata" },
  "бабочка": { en: "bow tie", es: "pajarita" },
  "очки": { en: "glasses", es: "gafas" },
  "солнцезащитные очки": { en: "sunglasses", es: "gafas de sol" },
  "часы": { en: "watch", es: "reloj" },
  "браслет": { en: "bracelet", es: "pulsera" },
  "кольцо": { en: "ring", es: "anillo" },
  "серьги": { en: "earrings", es: "pendientes" },
  "ожерелье": { en: "necklace", es: "collar" },
  "цепочка": { en: "chain", es: "cadena" },
  "кулон": { en: "pendant", es: "colgante" },
  "брошь": { en: "brooch", es: "broche" },
  "заколка": { en: "hair clip", es: "pasador" },
  "резинка для волос": { en: "hair tie", es: "coletero" },
  "сумка": { en: "bag", es: "bolso" },
  "рюкзак": { en: "backpack", es: "mochila" },
  "кошелёк": { en: "wallet", es: "cartera" },
  "зонт": { en: "umbrella", es: "paraguas" },
  "обувь": { en: "shoes", es: "zapatos" },
  "кроссовки": { en: "sneakers", es: "zapatillas" },
  "ботинки": { en: "boots", es: "botas" },
  "туфли": { en: "shoes", es: "zapatos" },

  // Musical Instruments
  "гитара": { en: "guitar", es: "guitarra" },
  "электрогитара": { en: "electric guitar", es: "guitarra eléctrica" },
  "бас-гитара": { en: "bass guitar", es: "bajo" },
  "акустическая гитара": { en: "acoustic guitar", es: "guitarra acústica" },
  "укулеле": { en: "ukulele", es: "ukelele" },
  "пианино": { en: "piano", es: "piano" },
  "рояль": { en: "grand piano", es: "piano de cola" },
  "синтезатор": { en: "synthesizer", es: "sintetizador" },
  "орган": { en: "organ", es: "órgano" },
  "аккордеон": { en: "accordion", es: "acordeón" },
  "баян": { en: "button accordion", es: "acordeón de botones" },
  "гармонь": { en: "harmonica", es: "armónica" },
  "скрипка": { en: "violin", es: "violín" },
  "альт": { en: "viola", es: "viola" },
  "виолончель": { en: "cello", es: "violonchelo" },
  "контрабас": { en: "double bass", es: "contrabajo" },
  "арфа": { en: "harp", es: "arpa" },
  "барабан": { en: "drum", es: "tambor" },
  "барабаны": { en: "drums", es: "batería" },
  "тарелки": { en: "cymbals", es: "platillos" },
  "тамбурин": { en: "tambourine", es: "pandereta" },
  "маракасы": { en: "maracas", es: "maracas" },
  "ксилофон": { en: "xylophone", es: "xilófono" },
  "металлофон": { en: "metallophone", es: "metalófono" },
  "колокольчик": { en: "bell", es: "campanilla" },
  "колокол": { en: "bell", es: "campana" },
  "треугольник": { en: "triangle", es: "triángulo" },
  "дудка": { en: "pipe", es: "flauta" },
  "флейта": { en: "flute", es: "flauta travesera" },
  "саксофон": { en: "saxophone", es: "saxofón" },
  "кларнет": { en: "clarinet", es: "clarinete" },
  "гобой": { en: "oboe", es: "oboe" },
  "фагот": { en: "bassoon", es: "fagot" },
  "труба": { en: "trumpet", es: "trompeta" },
  "тромбон": { en: "trombone", es: "trombón" },
  "валторна": { en: "french horn", es: "trompa" },
  "туба": { en: "tuba", es: "tuba" },
  "банджо": { en: "banjo", es: "banjo" },
  "мандолина": { en: "mandolin", es: "mandolina" },
  "балалайка": { en: "balalaika", es: "balalaika" },
  "домра": { en: "domra", es: "domra" },
  "гусли": { en: "gusli", es: "gusli" },
  "свирель": { en: "pipe", es: "caramillo" },
  "волынка": { en: "bagpipes", es: "gaita" },
  "губная гармошка": { en: "harmonica", es: "armónica" },
  "кастаньеты": { en: "castanets", es: "castañuelas" },
  "бубен": { en: "tambourine", es: "pandereta" },
  "гонг": { en: "gong", es: "gong" },
  "варган": { en: "jaw harp", es: "birimbao" },
  "диджериду": { en: "didgeridoo", es: "didgeridoo" },
  "терменвокс": { en: "theremin", es: "theremín" },
  "вибрафон": { en: "vibraphone", es: "vibráfono" },

  // Sport & Activities
  "футбол": { en: "football", es: "fútbol" },
  "баскетбол": { en: "basketball", es: "baloncesto" },
  "волейбол": { en: "volleyball", es: "voleibol" },
  "теннис": { en: "tennis", es: "tenis" },
  "настольный теннис": { en: "table tennis", es: "ping-pong" },
  "бадминтон": { en: "badminton", es: "bádminton" },
  "хоккей": { en: "hockey", es: "hockey" },
  "фигурное катание": { en: "figure skating", es: "patinaje artístico" },
  "бокс": { en: "boxing", es: "boxeo" },
  "борьба": { en: "wrestling", es: "lucha" },
  "дзюдо": { en: "judo", es: "judo" },
  "карате": { en: "karate", es: "karate" },
  "тхэквондо": { en: "taekwondo", es: "taekwondo" },
  "фехтование": { en: "fencing", es: "esgrima" },
  "стрельба": { en: "shooting", es: "tiro" },
  "стрельба из лука": { en: "archery", es: "tiro con arco" },
  "плавание": { en: "swimming", es: "natación" },
  "прыжки в воду": { en: "diving", es: "saltos" },
  "сёрфинг": { en: "surfing", es: "surf" },
  "гребля": { en: "rowing", es: "remo" },
  "парусный спорт": { en: "sailing", es: "vela" },
  "лыжи": { en: "skiing", es: "esquí" },
  "сноуборд": { en: "snowboarding", es: "snowboard" },
  "коньки": { en: "ice skating", es: "patinaje sobre hielo" },
  "бобслей": { en: "bobsleigh", es: "bobsleigh" },
  "биатлон": { en: "biathlon", es: "biatlón" },
  "лёгкая атлетика": { en: "athletics", es: "atletismo" },
  "бег": { en: "running", es: "correr" },
  "марафон": { en: "marathon", es: "maratón" },
  "прыжки в длину": { en: "long jump", es: "salto de longitud" },
  "прыжки в высоту": { en: "high jump", es: "salto de altura" },
  "метание копья": { en: "javelin throw", es: "lanzamiento de jabalina" },
  "толкание ядра": { en: "shot put", es: "lanzamiento de peso" },
  "спортивная гимнастика": { en: "gymnastics", es: "gimnasia artística" },
  "художественная гимнастика": { en: "rhythmic gymnastics", es: "gimnasia rítmica" },
  "тяжёлая атлетика": { en: "weightlifting", es: "halterofilia" },
  "пауэрлифтинг": { en: "powerlifting", es: "powerlifting" },
  "кроссфит": { en: "crossfit", es: "crossfit" },
  "йога": { en: "yoga", es: "yoga" },
  "пилатес": { en: "pilates", es: "pilates" },
  "велоспорт": { en: "cycling", es: "ciclismo" },
  "скейтбординг": { en: "skateboarding", es: "skateboarding" },
  "ролики": { en: "roller skating", es: "patinaje sobre ruedas" },
  "скалолазание": { en: "rock climbing", es: "escalada" },
  "альпинизм": { en: "mountaineering", es: "montañismo" },
  "паркур": { en: "parkour", es: "parkour" },
  "танцы": { en: "dancing", es: "baile" },
  "бальные танцы": { en: "ballroom dancing", es: "bailes de salón" },
  "брейк-данс": { en: "breakdancing", es: "breakdance" },
  "аэробика": { en: "aerobics", es: "aerobic" },
  "фитнес": { en: "fitness", es: "fitness" },
  "бодибилдинг": { en: "bodybuilding", es: "culturismo" },
  "регби": { en: "rugby", es: "rugby" },
  "гольф": { en: "golf", es: "golf" },
  "крикет": { en: "cricket", es: "críquet" },
  "бейсбол": { en: "baseball", es: "béisbol" },
  "шахматы": { en: "chess", es: "ajedrez" },

  // Household Items
  "книга": { en: "book", es: "libro" },
  "журнал": { en: "magazine", es: "revista" },
  "газета": { en: "newspaper", es: "periódico" },
  "каталог": { en: "catalog", es: "catálogo" },
  "реклама": { en: "advertisement", es: "publicidad" },
  "стол": { en: "table", es: "mesa" },
  "стул": { en: "chair", es: "silla" },
  "кресло": { en: "armchair", es: "sillón" },
  "диван": { en: "sofa", es: "sofá" },
  "кровать": { en: "bed", es: "cama" },
  "шкаф": { en: "wardrobe", es: "armario" },
  "тумбочка": { en: "nightstand", es: "mesita de noche" },
  "комод": { en: "dresser", es: "cómoda" },
  "полка": { en: "shelf", es: "estante" },
  "зеркало": { en: "mirror", es: "espejo" },
  "картина": { en: "painting", es: "cuadro" },
  "часы": { en: "clock", es: "reloj" },
  "лампа": { en: "lamp", es: "lámpara" },
  "люстра": { en: "chandelier", es: "lámpara de araña" },
  "телевизор": { en: "television", es: "televisor" },
  "пульт": { en: "remote control", es: "mando a distancia" },
  "кондиционер": { en: "air conditioner", es: "aire acondicionado" },
  "обогреватель": { en: "heater", es: "calefactor" },
  "вентилятор": { en: "fan", es: "ventilador" },
  "пылесос": { en: "vacuum cleaner", es: "aspiradora" },
  "веник": { en: "broom", es: "escoba" },
  "швабра": { en: "mop", es: "mopa" },
  "ведро": { en: "bucket", es: "cubo" },
  "таз": { en: "basin", es: "palangana" },
  "утюг": { en: "iron", es: "plancha" },
  "гладильная доска": { en: "ironing board", es: "tabla de planchar" },
  "стиральная машина": { en: "washing machine", es: "lavadora" },
  "сушилка": { en: "drying rack", es: "tendedero" },
  "прищепка": { en: "clothespin", es: "pinza de ropa" },
  "вешалка": { en: "hanger", es: "percha" },
  "подушка": { en: "pillow", es: "almohada" },
  "одеяло": { en: "blanket", es: "manta" },
  "простыня": { en: "sheet", es: "sábana" },
  "ковёр": { en: "carpet", es: "alfombra" },
  "занавеска": { en: "curtain", es: "cortina" },
  "скатерть": { en: "tablecloth", es: "mantel" },
  "салфетка": { en: "napkin", es: "servilleta" },
  "тарелка": { en: "plate", es: "plato" },
  "чашка": { en: "cup", es: "taza" },
  "стакан": { en: "glass", es: "vaso" },
  "кружка": { en: "mug", es: "tazón" },
  "ложка": { en: "spoon", es: "cuchara" },
  "вилка": { en: "fork", es: "tenedor" },
  "нож": { en: "knife", es: "cuchillo" },
  "кастрюля": { en: "pot", es: "olla" },
  "сковорода": { en: "frying pan", es: "sartén" },
  "чайник": { en: "kettle", es: "hervidor" },
  "холодильник": { en: "refrigerator", es: "nevera" },
  "микроволновка": { en: "microwave", es: "microondas" },
  "плита": { en: "stove", es: "cocina" },
  "духовка": { en: "oven", es: "horno" },
  "тостер": { en: "toaster", es: "tostadora" },
  "блендер": { en: "blender", es: "licuadora" },
  "миксер": { en: "mixer", es: "batidora" },
  "мультиварка": { en: "slow cooker", es: "olla de cocción lenta" },
  "разделочная доска": { en: "cutting board", es: "tabla de cortar" },
  "полотенце": { en: "towel", es: "toalla" },
  "зубная щётка": { en: "toothbrush", es: "cepillo de dientes" },
  "расчёска": { en: "comb", es: "peine" },
  "фен": { en: "hairdryer", es: "secador" },

  // Technology & Gadgets
  "телефон": { en: "phone", es: "teléfono" },
  "смартфон": { en: "smartphone", es: "smartphone" },
  "планшет": { en: "tablet", es: "tableta" },
  "ноутбук": { en: "laptop", es: "portátil" },
  "компьютер": { en: "computer", es: "computadora" },
  "монитор": { en: "monitor", es: "monitor" },
  "клавиатура": { en: "keyboard", es: "teclado" },
  "мышь": { en: "mouse", es: "ratón" },
  "принтер": { en: "printer", es: "impresora" },
  "сканер": { en: "scanner", es: "escáner" },
  "наушники": { en: "headphones", es: "auriculares" },
  "микрофон": { en: "microphone", es: "micrófono" },
  "колонка": { en: "speaker", es: "altavoz" },
  "камера": { en: "camera", es: "cámara" },
  "видеокамера": { en: "video camera", es: "videocámara" },
  "проектор": { en: "projector", es: "proyector" },
  "роутер": { en: "router", es: "router" },
  "модем": { en: "modem", es: "módem" },
  "флешка": { en: "flash drive", es: "memoria USB" },
  "внешний диск": { en: "external hard drive", es: "disco duro externo" },
  "карта памяти": { en: "memory card", es: "tarjeta de memoria" },
  "зарядное устройство": { en: "charger", es: "cargador" },
  "кабель": { en: "cable", es: "cable" },
  "удлинитель": { en: "extension cord", es: "alargador" },
  "переходник": { en: "adapter", es: "adaptador" },
  "пауэрбанк": { en: "power bank", es: "batería externa" },
  "смарт-часы": { en: "smartwatch", es: "reloj inteligente" },
  "фитнес-браслет": { en: "fitness tracker", es: "pulsera de actividad" },
  "беспроводные наушники": { en: "wireless earbuds", es: "auriculares inalámbricos" },
  "колонка блютус": { en: "bluetooth speaker", es: "altavoz bluetooth" },
  "игровая приставка": { en: "game console", es: "consola de juegos" },
  "джойстик": { en: "joystick", es: "joystick" },
  "геймпад": { en: "gamepad", es: "gamepad" },
  "виртуальная реальность": { en: "VR headset", es: "gafas de realidad virtual" },
  "дрон": { en: "drone", es: "dron" },
  "квадрокоптер": { en: "quadcopter", es: "cuadricóptero" },
  "3D-принтер": { en: "3D printer", es: "impresora 3D" },
  "робот-пылесос": { en: "robot vacuum", es: "robot aspirador" },
  "умная лампа": { en: "smart bulb", es: "bombilla inteligente" },
  "умная колонка": { en: "smart speaker", es: "altavoz inteligente" },
  "умный замок": { en: "smart lock", es: "cerradura inteligente" },
  "термостат": { en: "thermostat", es: "termostato" },
  "датчик движения": { en: "motion sensor", es: "sensor de movimiento" },
  "электронная книга": { en: "e-reader", es: "libro electrónico" },
  "цифровой фотоаппарат": { en: "digital camera", es: "cámara digital" },
  "экшн-камера": { en: "action camera", es: "cámara de acción" },
  "веб-камера": { en: "webcam", es: "webcam" },
  "графический планшет": { en: "graphics tablet", es: "tableta gráfica" },
  "стилус": { en: "stylus", es: "lápiz óptico" },
  "клавиатура с подсветкой": { en: "backlit keyboard", es: "teclado retroiluminado" },
  "игровая мышь": { en: "gaming mouse", es: "ratón gaming" },
  "коврик для мыши": { en: "mousepad", es: "alfombrilla para ratón" },
  "ноутбучная подставка": { en: "laptop stand", es: "soporte para portátil" },
  "охлаждающая подставка": { en: "cooling pad", es: "base refrigeradora" },
  "USB-хаб": { en: "USB hub", es: "concentrador USB" },
  "сетевая карта": { en: "network card", es: "tarjeta de red" },
  "ИБП": { en: "UPS", es: "SAI" },
  "сервер": { en: "server", es: "servidor" },

  // Weather
  "погода": { en: "weather", es: "tiempo" },
  "солнечно": { en: "sunny", es: "soleado" },
  "облачно": { en: "cloudy", es: "nublado" },
  "дождливо": { en: "rainy", es: "lluvioso" },
  "ливень": { en: "downpour", es: "aguacero" },
  "снежно": { en: "snowy", es: "nevado" },
  "ветрено": { en: "windy", es: "ventoso" },
  "туманно": { en: "foggy", es: "con niebla" },
  "шторм": { en: "storm", es: "tormenta" },
  "метель": { en: "blizzard", es: "ventisca" },
  "пурга": { en: "snowstorm", es: "tormenta de nieve" },
  "буря": { en: "tempest", es: "tempestad" },
  "циклон": { en: "cyclone", es: "ciclón" },
  "антициклон": { en: "anticyclone", es: "anticiclón" },
  "жара": { en: "hot", es: "caluroso" },
  "тепло": { en: "warm", es: "cálido" },
  "прохладно": { en: "cool", es: "fresco" },
  "холод": { en: "cold", es: "frío" },
  "холодно": { en: "cold", es: "hace frío" },
  "морозно": { en: "frosty", es: "helado" },
  "гололёд": { en: "black ice", es: "hielo negro" },
  "слякоть": { en: "slush", es: "aguanieve" },
  "влажно": { en: "humid", es: "húmedo" },
  "влажность": { en: "humidity", es: "humedad" },
  "сухо": { en: "dry", es: "seco" },
  "ясно": { en: "clear", es: "despejado" },
  "пасмурно": { en: "overcast", es: "cubierto" },
  "переменная облачность": { en: "partly cloudy", es: "parcialmente nublado" },

  // City & Places
  "город": { en: "city", es: "ciudad" },
  "деревня": { en: "village", es: "pueblo" },
  "посёлок": { en: "town", es: "pueblo" },
  "столица": { en: "capital", es: "capital" },
  "улица": { en: "street", es: "calle" },
  "проспект": { en: "avenue", es: "avenida" },
  "площадь": { en: "square", es: "plaza" },
  "перекрёсток": { en: "crossroads", es: "cruce" },
  "светофор": { en: "traffic light", es: "semáforo" },
  "пешеходный переход": { en: "crosswalk", es: "paso de peatones" },
  "тротуар": { en: "sidewalk", es: "acera" },
  "мост": { en: "bridge", es: "puente" },
  "набережная": { en: "embankment", es: "malecón" },
  "парк": { en: "park", es: "parque" },
  "сквер": { en: "square", es: "plazoleta" },
  "сад": { en: "garden", es: "jardín" },
  "фонтан": { en: "fountain", es: "fuente" },
  "памятник": { en: "monument", es: "monumento" },
  "статуя": { en: "statue", es: "estatua" },
  "здание": { en: "building", es: "edificio" },
  "небоскрёб": { en: "skyscraper", es: "rascacielos" },
  "дом": { en: "house", es: "casa" },
  "квартира": { en: "apartment", es: "apartamento" },
  "подъезд": { en: "entrance", es: "entrada" },
  "лифт": { en: "elevator", es: "ascensor" },
  "лестница": { en: "stairs", es: "escaleras" },
  "двор": { en: "yard", es: "patio" },
  "детская площадка": { en: "playground", es: "parque infantil" },
  "остановка": { en: "bus stop", es: "parada de autobús" },
  "вокзал": { en: "train station", es: "estación de tren" },
  "аэропорт": { en: "airport", es: "aeropuerto" },
  "порт": { en: "port", es: "puerto" },
  "больница": { en: "hospital", es: "hospital" },
  "поликлиника": { en: "clinic", es: "clínica" },
  "аптека": { en: "pharmacy", es: "farmacia" },
  "школа": { en: "school", es: "escuela" },
  "университет": { en: "university", es: "universidad" },
  "библиотека": { en: "library", es: "biblioteca" },
  "музей": { en: "museum", es: "museo" },
  "театр": { en: "theater", es: "teatro" },
  "кинотеатр": { en: "cinema", es: "cine" },
  "цирк": { en: "circus", es: "circo" },
  "зоопарк": { en: "zoo", es: "zoológico" },
  "стадион": { en: "stadium", es: "estadio" },
  "бассейн": { en: "swimming pool", es: "piscina" },
  "спортзал": { en: "gym", es: "gimnasio" },
  "магазин": { en: "store", es: "tienda" },
  "супермаркет": { en: "supermarket", es: "supermercado" },
  "рынок": { en: "market", es: "mercado" },
  "торговый центр": { en: "shopping mall", es: "centro comercial" },
  "ресторан": { en: "restaurant", es: "restaurante" },
  "кафе": { en: "cafe", es: "cafetería" },
  "бар": { en: "bar", es: "bar" },
  "гостиница": { en: "hotel", es: "hotel" },
  "банк": { en: "bank", es: "banco" },
  "банкомат": { en: "ATM", es: "cajero automático" },
  "почта": { en: "post office", es: "oficina de correos" },
  "полиция": { en: "police station", es: "comisaría" },
  "пожарная часть": { en: "fire station", es: "estación de bomberos" },
  "церковь": { en: "church", es: "iglesia" },
  "кладбище": { en: "cemetery", es: "cementerio" },
  "завод": { en: "factory", es: "fábrica" }
};

const emojiMap = {
// Animals Emoji
  "cat": "🐱",
  "dog": "🐶",
  "mouse": "🐭",
  "rat": "🐀",
  "hamster": "🐹",
  "rabbit": "🐰",
  "fox": "🦊",
  "wolf": "🐺",
  "bear": "🐻",
  "tiger": "🐯",
  "lion": "🦁",
  "panther": "🐆",
  "leopard": "🐆",
  "cheetah": "🐆",
  "elephant": "🐘",
  "giraffe": "🦒",
  "zebra": "🦓",
  "horse": "🐴",
  "pony": "🐴",
  "donkey": "🫏",
  "cow": "🐮",
  "bull": "🐂",
  "pig": "🐷",
  "boar": "🐗",
  "sheep": "🐑",
  "ram": "🐏",
  "goat": "🐐",
  "deer": "🦌",
  "moose": "🫎",
  "antelope": "🦌",
  "buffalo": "🐃",
  "hippo": "🦛",
  "rhino": "🦏",
  "monkey": "🐵",
  "gorilla": "🦍",
  "chimpanzee": "🐵",
  "sloth": "🦥",
  "koala": "🐨",
  "kangaroo": "🦘",
  "panda": "🐼",
  "raccoon": "🦝",
  "badger": "🦡",
  "beaver": "🦫",
  "otter": "🦦",
  "squirrel": "🐿️",
  "hedgehog": "🦔",
  "mole": "🐾",
  "bat": "🦇",
  "camel": "🐫",
  "llama": "🦙",
  "alpaca": "🦙",
  "chicken": "🐔",
  "rooster": "🐓",
  "duck": "🦆",
  "goose": "🪿",
  "turkey": "🦃",
  "swan": "🦢",
  "peacock": "🦚",
  "flamingo": "🦩",
  "penguin": "🐧",
  "ostrich": "🪶",
  "sparrow": "🐦",
  "pigeon": "🕊️",
  "crow": "🐦‍⬛",
  "magpie": "🐦",
  "owl": "🦉",
  "eagle": "🦅",
  "hawk": "🦅",
  "falcon": "🦅",
  "parrot": "🦜",
  "canary": "🐤",
  "hummingbird": "🐦",
  "seagull": "🐦",
  "crane": "🪿",
  "stork": "🕊️",
  "fish": "🐟",
  "shark": "🦈",
  "whale": "🐳",
  "dolphin": "🐬",
  "octopus": "🐙",
  "squid": "🦑",
  "crab": "🦀",
  "lobster": "🦞",
  "shrimp": "🦐",
  "starfish": "⭐",
  "jellyfish": "🪼",
  "seahorse": "🐠",
  "eel": "🐍",
  "ray": "🐟",
  "turtle": "🐢",
  "crocodile": "🐊",
  "alligator": "🐊",
  "snake": "🐍",
  "python": "🐍",
  "lizard": "🦎",
  "chameleon": "🦎",
  "iguana": "🦎",
  "frog": "🐸",
  "toad": "🐸",
  "salamander": "🦎",
  "butterfly": "🦋",
  "bee": "🐝",
  "wasp": "🐝",
  "bumblebee": "🐝",
  "ant": "🐜",
  "spider": "🕷️",
  "scorpion": "🦂",
  "cockroach": "🪳",
  "fly": "🪰",
  "mosquito": "🦟",
  "dragonfly": "🪰",
  "grasshopper": "🦗",
  "cricket": "🦗",
  "beetle": "🪲",
  "ladybug": "🐞",
  "caterpillar": "🐛",
  "snail": "🐌",
  "slug": "🐌",
  "worm": "🪱",
  // Professions Emoji
  "doctor": "🧑‍⚕️",
  "teacher": "🧑‍🏫",
  "firefighter": "🧑‍🚒",
  "police officer": "👮",
  "chef": "🧑‍🍳",
  "artist": "🧑‍🎨",
  "musician": "🧑‍🎤",
  "pilot": "🧑‍✈️",
  "programmer": "🧑‍💻",
  "scientist": "🧑‍🔬",
  "construction worker": "👷",
  "engineer": "🧑‍🔧",
  "driver": "🧑‍✈️",
  "nurse": "🧑‍⚕️",
  "pharmacist": "💊",
  "veterinarian": "🐾",
  "dentist": "🦷",
  "psychologist": "🧠",
  "lawyer": "⚖️",
  "judge": "🧑‍⚖️",
  "journalist": "📰",
  "writer": "✍️",
  "actor": "🎭",
  "director": "🎬",
  "photographer": "📷",
  "designer": "🎨",
  "architect": "📐",
  "accountant": "📊",
  "translator": "🌐",
  "diplomat": "🤝",
  "lifeguard": "🛟",
  "detective": "🕵️",
  "surgeon": "🔪",
  "electrician": "💡",
  "plumber": "🔧",
  "mechanic": "🔩",
  "welder": "🔥",
  "farmer": "🧑‍🌾",
  "baker": "🥖",
  "pastry chef": "🎂",
  "butcher": "🥩",
  "hairdresser": "💇",
  "stylist": "👗",
  "makeup artist": "💄",
  "coach": "📋",
  "athlete": "🏃",
  "barista": "☕",
  "waiter": "🍽️",
  "flight attendant": "✈️",
  "secretary": "📞",
  "manager": "💼",
  "entrepreneur": "🚀",
  "military officer": "🪖",
  // Nature & Weather Emoji
  "sun": "☀️",
  "rain": "🌧️",
  "snow": "❄️",
  "wind": "💨",
  "cloud": "☁️",
  "thunderstorm": "⛈️",
  "lightning": "⚡",
  "thunder": "🌩️",
  "hail": "🌨️",
  "fog": "🌫️",
  "rainbow": "🌈",
  "hurricane": "🌀",
  "tornado": "🌪️",
  "drought": "🏜️",
  "flood": "🌊",
  "heat": "🥵",
  "frost": "🥶",
  "ice": "🧊",
  "sky": "🌌",
  "star": "⭐",
  "moon": "🌙",
  "planet": "🪐",
  "earth": "🌍",
  "air": "💨",
  "water": "💧",
  "fire": "🔥",
  "forest": "🌲",
  "tree": "🌳",
  "leaf": "🍃",
  "flower": "🌸",
  "grass": "🌿",
  "bush": "🪴",
  "mountain": "⛰️",
  "hill": "🏔️",
  "valley": "🏞️",
  "field": "🌾",
  "meadow": "🌼",
  "river": "🏞️",
  "lake": "🌊",
  "sea": "🌊",
  "ocean": "🌏",
  "island": "🏝️",
  "peninsula": "🗾",
  "beach": "🏖️",
  "desert": "🏜️",
  "waterfall": "💦",
  "volcano": "🌋",
  "iceberg": "🧊",
  "cave": "🕳️",
  "rock": "🪨",
  "stone": "🪨",
  "sand": "🏝️",
  "mud": "🟤",
  "soil": "🟫",
  "dew": "💧",
  "icicle": "🧊",
  // Transport Emoji
  "car": "🚗",
  "automobile": "🚘",
  "bus": "🚌",
  "trolleybus": "🚎",
  "tram": "🚋",
  "train": "🚂",
  "suburban train": "🚆",
  "subway": "🚇",
  "airplane": "✈️",
  "helicopter": "🚁",
  "ship": "🚢",
  "boat": "⛵",
  "motorboat": "🛥️",
  "yacht": "🛳️",
  "ferry": "⛴️",
  "submarine": "🔱",
  "bicycle": "🚲",
  "motorcycle": "🏍️",
  "moped": "🛵",
  "scooter": "🛴",
  "kick scooter": "🛴",
  "taxi": "🚕",
  "truck": "🚛",
  "semi-truck": "🚚",
  "dump truck": "🛻",
  "excavator": "🚧",
  "bulldozer": "🚜",
  "tractor": "🚜",
  "ambulance": "🚑",
  "fire truck": "🚒",
  "police car": "🚓",
  "tow truck": "🛻",
  "fuel truck": "⛽",
  "minibus": "🚐",
  "SUV": "🚙",
  "convertible": "🏎️",
  "limousine": "🚘",
  "go-kart": "🏎️",
  "ATV": "🛻",
  "snowmobile": "🛷",
  "airship": "🛸",
  "hot air balloon": "🎈",
  "hang glider": "🪂",
  "cable car": "🚡",
  "funicular": "🚞",
  "tank": "🪖",
  "armored vehicle": "🛡️",
  "rocket": "🚀",
  "spaceship": "🛸",
  "satellite": "🛰️",
  "kayak": "🛶",
  "canoe": "🛶",
  "catamaran": "⛵",
  "jet ski": "🛥️",
  "commuter train": "🚆",
  // Clothes & Accessories Emoji
  "clothes": "👗",
  "t-shirt": "👕",
  "shirt": "👔",
  "blouse": "👚",
  "sweater": "🧥",
  "hoodie": "🦺",
  "jacket": "🧥",
  "coat": "🧥",
  "raincoat": "🧥",
  "fur coat": "🧥",
  "vest": "🦺",
  "blazer": "🤵",
  "suit": "🤵",
  "jeans": "👖",
  "trousers": "👖",
  "shorts": "🩳",
  "pants": "👖",
  "skirt": "👗",
  "dress": "👗",
  "sundress": "👗",
  "overalls": "👖",
  "underwear": "🩲",
  "bra": "👙",
  "socks": "🧦",
  "knee socks": "🧦",
  "tights": "🧦",
  "pajamas": "🌙",
  "robe": "👘",
  "swimsuit": "👙",
  "swim trunks": "🩳",
  "hat": "🧢",
  "cap": "🧢",
  "beret": "👒",
  "scarf": "🧣",
  "gloves": "🧤",
  "mittens": "🧤",
  "belt": "🪢",
  "tie": "👔",
  "bow tie": "🎀",
  "glasses": "👓",
  "sunglasses": "🕶️",
  "watch": "⌚",
  "bracelet": "📿",
  "ring": "💍",
  "earrings": "💎",
  "necklace": "📿",
  "chain": "⛓️",
  "pendant": "🔮",
  "brooch": "🧷",
  "hair clip": "📎",
  "hair tie": "🎗️",
  "bag": "👜",
  "backpack": "🎒",
  "wallet": "👛",
  "umbrella": "☂️",
  "shoes": "👞",
  "sneakers": "👟",
  "boots": "🥾",
  "purse": "👝",
  // Musical Instruments Emoji
  "guitar": "🎸",
  "electric guitar": "🎸",
  "bass guitar": "🎸",
  "acoustic guitar": "🎸",
  "ukulele": "🪕",
  "piano": "🎹",
  "grand piano": "🎹",
  "synthesizer": "🎹",
  "organ": "🪗",
  "accordion": "🪗",
  "button accordion": "🪗",
  "harmonica": "🎹",
  "violin": "🎻",
  "viola": "🎻",
  "cello": "🎻",
  "double bass": "🎻",
  "harp": "🎼",
  "drum": "🥁",
  "drums": "🥁",
  "cymbals": "🎶",
  "tambourine": "🥁",
  "maracas": "🎵",
  "xylophone": "🎼",
  "metallophone": "🎹",
  "bell": "🔔",
  "triangle": "🔺",
  "pipe": "🎵",
  "flute": "🎵",
  "saxophone": "🎷",
  "clarinet": "🎵",
  "oboe": "🎵",
  "bassoon": "🎵",
  "trumpet": "🎺",
  "trombone": "🎺",
  "french horn": "📯",
  "tuba": "📯",
  "banjo": "🪕",
  "mandolin": "🪕",
  "balalaika": "🎵",
  "domra": "🎵",
  "gusli": "🎼",
  "bagpipes": "🎵",
  "castanets": "🪇",
  "gong": "🪘",
  "jaw harp": "🎵",
  "didgeridoo": "🪈",
  "theremin": "🎛️",
  "vibraphone": "🎹",
  // Sport & Activities Emoji
  "football": "⚽",
  "basketball": "🏀",
  "volleyball": "🏐",
  "tennis": "🎾",
  "table tennis": "🏓",
  "badminton": "🏸",
  "hockey": "🏒",
  "figure skating": "⛸️",
  "boxing": "🥊",
  "wrestling": "🤼",
  "judo": "🥋",
  "karate": "🥋",
  "taekwondo": "🥋",
  "fencing": "🤺",
  "shooting": "🎯",
  "archery": "🏹",
  "swimming": "🏊",
  "diving": "🤿",
  "surfing": "🏄",
  "rowing": "🚣",
  "sailing": "⛵",
  "skiing": "⛷️",
  "snowboarding": "🏂",
  "ice skating": "⛸️",
  "bobsleigh": "🛷",
  "biathlon": "🎿",
  "athletics": "🏃",
  "running": "🏃",
  "marathon": "🏃",
  "long jump": "📏",
  "high jump": "📐",
  "javelin throw": "🏹",
  "shot put": "💪",
  "gymnastics": "🤸",
  "rhythmic gymnastics": "🤸",
  "weightlifting": "🏋️",
  "powerlifting": "🏋️",
  "crossfit": "🏋️",
  "yoga": "🧘",
  "pilates": "🧘",
  "cycling": "🚴",
  "skateboarding": "🛹",
  "roller skating": "🛼",
  "rock climbing": "🧗",
  "mountaineering": "🧗",
  "parkour": "🏃",
  "dancing": "💃",
  "ballroom dancing": "💃",
  "breakdancing": "🕺",
  "aerobics": "🤸",
  "fitness": "💪",
  "bodybuilding": "💪",
  "rugby": "🏉",
  "golf": "⛳",
  "cricket": "🏏",
  "baseball": "⚾",
  "chess": "♟️",
  // Household Items Emoji
  "book": " 📖 ",
  "magazine":" 📰 ",
  "newspaper":" 📰 ",
  "catalog": " 📚 ",
  "advertisement": " 📰 ",
  "table": "🪑",
  "chair": "🪑",
  "armchair": "🛋️",
  "sofa": "🛋️",
  "bed": "🛏️",
  "wardrobe": "🗄️",
  "nightstand": "🛏️",
  "dresser": "🗄️",
  "shelf": "📚",
  "mirror": "🪞",
  "painting": "🖼️",
  "clock": "⏰",
  "lamp": "💡",
  "chandelier": "💡",
  "television": "📺",
  "remote control": "🔘",
  "air conditioner": "🌬️",
  "heater": "🔥",
  "fan": "🪭",
  "vacuum cleaner": "🧹",
  "broom": "🧹",
  "mop": "🧹",
  "bucket": "🪣",
  "basin": "🪣",
  "iron": "👕",
  "ironing board": "👕",
  "washing machine": "🧺",
  "drying rack": "🧺",
  "clothespin": "📎",
  "hanger": "👔",
  "pillow": "🛌",
  "blanket": "🛌",
  "sheet": "🛏️",
  "carpet": "🟫",
  "curtain": "🪟",
  "tablecloth": "🍽️",
  "napkin": "🍽️",
  "plate": "🍽️",
  "cup": "☕",
  "glass": "🥛",
  "mug": "☕",
  "spoon": "🥄",
  "fork": "🍴",
  "knife": "🔪",
  "pot": "🍲",
  "frying pan": "🍳",
  "kettle": "🫖",
  "refrigerator": "🧊",
  "microwave": "📡",
  "stove": "🔥",
  "oven": "🔥",
  "toaster": "🍞",
  "blender": "🥤",
  "mixer": "🥤",
  "slow cooker": "🍲",
  "cutting board": "🔪",
  "towel": "🧻",
  "toothbrush": "🪥",
  "comb": "🪮",
  "hairdryer": "💨",
  // Technology & Gadgets Emoji
  "phone": "📱",
  "smartphone": "📱",
  "tablet": "📱",
  "laptop": "💻",
  "computer": "🖥️",
  "monitor": "🖥️",
  "keyboard": "⌨️",
  "mouse": "🖱️",
  "printer": "🖨️",
  "scanner": "🖨️",
  "headphones": "🎧",
  "microphone": "🎤",
  "speaker": "🔊",
  "camera": "📷",
  "video camera": "📹",
  "projector": "📽️",
  "router": "📡",
  "modem": "📡",
  "flash drive": "💾",
  "external hard drive": "💽",
  "memory card": "💾",
  "charger": "🔌",
  "cable": "🔌",
  "extension cord": "🔌",
  "adapter": "🔌",
  "power bank": "🔋",
  "smartwatch": "⌚",
  "fitness tracker": "⌚",
  "wireless earbuds": "🎧",
  "bluetooth speaker": "🔊",
  "game console": "🎮",
  "joystick": "🕹️",
  "gamepad": "🎮",
  "VR headset": "🥽",
  "drone": "🛸",
  "quadcopter": "🛸",
  "3D printer": "🖨️",
  "robot vacuum": "🤖",
  "smart bulb": "💡",
  "smart speaker": "🔊",
  "smart lock": "🔐",
  "thermostat": "🌡️",
  "motion sensor": "📳",
  "e-reader": "📖",
  "digital camera": "📸",
  "action camera": "📸",
  "webcam": "📹",
  "graphics tablet": "🎨",
  "stylus": "🖊️",
  "backlit keyboard": "⌨️",
  "gaming mouse": "🖱️",
  "mousepad": "🖱️",
  "laptop stand": "💻",
  "cooling pad": "❄️",
  "USB hub": "🔌",
  "network card": "🌐",
  "UPS": "🔋",
  "server": "🗄️",
  // Weather Emoji
  "weather": "🌤️",
  "sun": "☀️",
  "sunny": "☀️",
  "cloud": "☁️",
  "cloudy": "☁️",
  "rain": "🌧️",
  "rainy": "🌧️",
  "downpour": "🌧️",
  "snow": "❄️",
  "snowy": "🌨️",
  "hail": "🌨️",
  "wind": "💨",
  "windy": "💨",
  "fog": "🌫️",
  "foggy": "🌫️",
  "thunderstorm": "⛈️",
  "lightning": "⚡",
  "thunder": "🌩️",
  "rainbow": "🌈",
  "hurricane": "🌀",
  "tornado": "🌪️",
  "storm": "⛈️",
  "blizzard": "🌨️",
  "snowstorm": "🌨️",
  "tempest": "⛈️",
  "cyclone": "🌀",
  "anticyclone": "☀️",
  "drought": "🏜️",
  "flood": "🌊",
  "heat": "🥵",
  "hot": "🥵",
  "warm": "🌡️",
  "cool": "😌",
  "cold": "🥶",
  "frost": "🥶",
  "frosty": "🥶",
  "ice": "🧊",
  "black ice": "🧊",
  "icicle": "🧊",
  "slush": "💧",
  "humid": "💧",
  "humidity": "💧",
  "dry": "🏜️",
  "dew": "💧",
  "sky": "🌌",
  "clear": "🌙",
  "overcast": "☁️",
  "partly cloudy": "⛅",
  // City & Places Emoji
  "city": "🏙️",
  "village": "🏘️",
  "town": "🏘️",
  "capital": "🏛️",
  "street": "🛣️",
  "avenue": "🛣️",
  "square": "⛲",
  "crossroads": "🚦",
  "traffic light": "🚦",
  "crosswalk": "🚸",
  "sidewalk": "🚶",
  "bridge": "🌉",
  "embankment": "🏞️",
  "park": "🏞️",
  "square": "🏙️",
  "garden": "🌳",
  "fountain": "⛲",
  "monument": "🗿",
  "statue": "🗿",
  "building": "🏢",
  "skyscraper": "🏢",
  "house": "🏠",
  "apartment": "🏢",
  "entrance": "🚪",
  "elevator": "🛗",
  "stairs": "🪜",
  "yard": "🏡",
  "playground": "🛝",
  "bus stop": "🚏",
  "train station": "🚉",
  "airport": "✈️",
  "port": "⚓",
  "hospital": "🏥",
  "clinic": "🏥",
  "pharmacy": "💊",
  "school": "🏫",
  "university": "🎓",
  "library": "📚",
  "museum": "🏛️",
  "theater": "🎭",
  "cinema": "🎬",
  "circus": "🎪",
  "zoo": "🦁",
  "stadium": "🏟️",
  "swimming pool": "🏊",
  "gym": "🏋️",
  "store": "🏪",
  "supermarket": "🏪",
  "market": "🛒",
  "shopping mall": "🏬",
  "restaurant": "🍽️",
  "cafe": "☕",
  "bar": "🍺",
  "hotel": "🏨",
  "bank": "🏦",
  "ATM": "🏧",
  "post office": "🏤",
  "police station": "🚔",
  "fire station": "🚒",
  "church": "⛪",
  "cemetery": "🪦",
  "factory": "🏭"
};
