const dictionary = {
  // Animals Dictionary
  "кот": "cat",
  "собака": "dog",
  "мышь": "mouse",
  "крыса": "rat",
  "хомяк": "hamster",
  "кролик": "rabbit",
  "лиса": "fox",
  "волк": "wolf",
  "медведь": "bear",
  "тигр": "tiger",
  "лев": "lion",
  "пантера": "panther",
  "леопард": "leopard",
  "гепард": "cheetah",
  "слон": "elephant",
  "жираф": "giraffe",
  "зебра": "zebra",
  "лошадь": "horse",
  "пони": "pony",
  "осёл": "donkey",
  "корова": "cow",
  "бык": "bull",
  "свинья": "pig",
  "кабан": "boar",
  "овца": "sheep",
  "баран": "ram",
  "коза": "goat",
  "олень": "deer",
  "лось": "moose",
  "антилопа": "antelope",
  "буйвол": "buffalo",
  "бегемот": "hippo",
  "носорог": "rhino",
  "обезьяна": "monkey",
  "горилла": "gorilla",
  "шимпанзе": "chimpanzee",
  "ленивец": "sloth",
  "коала": "koala",
  "кенгуру": "kangaroo",
  "панда": "panda",
  "енот": "raccoon",
  "барсук": "badger",
  "бобр": "beaver",
  "выдра": "otter",
  "белка": "squirrel",
  "ёж": "hedgehog",
  "крот": "mole",
  "летучая мышь": "bat",
  "верблюд": "camel",
  "лама": "llama",
  "альпака": "alpaca",
  "курица": "chicken",
  "петух": "rooster",
  "утка": "duck",
  "гусь": "goose",
  "индюк": "turkey",
  "лебедь": "swan",
  "павлин": "peacock",
  "фламинго": "flamingo",
  "пингвин": "penguin",
  "страус": "ostrich",
  "воробей": "sparrow",
  "голубь": "pigeon",
  "ворона": "crow",
  "сорока": "magpie",
  "сова": "owl",
  "орёл": "eagle",
  "ястреб": "hawk",
  "сокол": "falcon",
  "попугай": "parrot",
  "канарейка": "canary",
  "колибри": "hummingbird",
  "чайка": "seagull",
  "журавль": "crane",
  "аист": "stork",
  "рыба": "fish",
  "акула": "shark",
  "кит": "whale",
  "дельфин": "dolphin",
  "осьминог": "octopus",
  "кальмар": "squid",
  "краб": "crab",
  "омар": "lobster",
  "креветка": "shrimp",
  "морская звезда": "starfish",
  "медуза": "jellyfish",
  "морской конёк": "seahorse",
  "угорь": "eel",
  "скат": "ray",
  "черепаха": "turtle",
  "крокодил": "crocodile",
  "аллигатор": "alligator",
  "змея": "snake",
  "питон": "python",
  "ящерица": "lizard",
  "хамелеон": "chameleon",
  "игуана": "iguana",
  "лягушка": "frog",
  "жаба": "toad",
  "саламандра": "salamander",
  "бабочка": "butterfly",
  "пчела": "bee",
  "оса": "wasp",
  "шмель": "bumblebee",
  "муравей": "ant",
  "паук": "spider",
  "скорпион": "scorpion",
  "таракан": "cockroach",
  "муха": "fly",
  "комар": "mosquito",
  "стрекоза": "dragonfly",
  "кузнечик": "grasshopper",
  "сверчок": "cricket",
  "жук": "beetle",
  "божья коровка": "ladybug",
  "гусеница": "caterpillar",
  "улитка": "snail",
  "слизень": "slug",
  "червь": "worm",
  // Professions Dictionary
  "врач": "doctor",
  "учитель": "teacher",
  "пожарный": "firefighter",
  "полицейский": "police officer",
  "повар": "chef",
  "художник": "artist",
  "музыкант": "musician",
  "пилот": "pilot",
  "программист": "programmer",
  "учёный": "scientist",
  "строитель": "construction worker",
  "инженер": "engineer",
  "водитель": "driver",
  "медсестра": "nurse",
  "аптекарь": "pharmacist",
  "ветеринар": "veterinarian",
  "стоматолог": "dentist",
  "психолог": "psychologist",
  "юрист": "lawyer",
  "судья": "judge",
  "журналист": "journalist",
  "писатель": "writer",
  "актёр": "actor",
  "режиссёр": "director",
  "фотограф": "photographer",
  "дизайнер": "designer",
  "архитектор": "architect",
  "бухгалтер": "accountant",
  "переводчик": "translator",
  "дипломат": "diplomat",
  "спасатель": "lifeguard",
  "детектив": "detective",
  "хирург": "surgeon",
  "фармацевт": "pharmacist",
  "электрик": "electrician",
  "сантехник": "plumber",
  "механик": "mechanic",
  "сварщик": "welder",
  "фермер": "farmer",
  "пекарь": "baker",
  "кондитер": "pastry chef",
  "мясник": "butcher",
  "парикмахер": "hairdresser",
  "стилист": "stylist",
  "визажист": "makeup artist",
  "тренер": "coach",
  "спортсмен": "athlete",
  "бариста": "barista",
  "официант": "waiter",
  "стюардесса": "flight attendant",
  "секретарь": "secretary",
  "менеджер": "manager",
  "предприниматель": "entrepreneur",
  "военный": "military officer",
  // Nature & Weather Dictionary
  "солнце": "sun",
  "дождь": "rain",
  "снег": "snow",
  "ветер": "wind",
  "облако": "cloud",
  "гроза": "thunderstorm",
  "молния": "lightning",
  "гром": "thunder",
  "град": "hail",
  "туман": "fog",
  "радуга": "rainbow",
  "ураган": "hurricane",
  "торнадо": "tornado",
  "засуха": "drought",
  "наводнение": "flood",
  "жара": "heat",
  "мороз": "frost",
  "лёд": "ice",
  "небо": "sky",
  "звезда": "star",
  "луна": "moon",
  "планета": "planet",
  "земля": "earth",
  "воздух": "air",
  "вода": "water",
  "огонь": "fire",
  "лес": "forest",
  "дерево": "tree",
  "лист": "leaf",
  "цветок": "flower",
  "трава": "grass",
  "куст": "bush",
  "гора": "mountain",
  "холм": "hill",
  "долина": "valley",
  "поле": "field",
  "луг": "meadow",
  "река": "river",
  "озеро": "lake",
  "море": "sea",
  "океан": "ocean",
  "остров": "island",
  "полуостров": "peninsula",
  "пляж": "beach",
  "пустыня": "desert",
  "водопад": "waterfall",
  "вулкан": "volcano",
  "айсберг": "iceberg",
  "пещера": "cave",
  "скала": "rock",
  "камень": "stone",
  "песок": "sand",
  "грязь": "mud",
  "почва": "soil",
  "роса": "dew",
  "сосулька": "icicle",
  // Transport Dictionary
  "машина": "car",
  "автомобиль": "automobile",
  "автобус": "bus",
  "троллейбус": "trolleybus",
  "трамвай": "tram",
  "поезд": "train",
  "электричка": "suburban train",
  "метро": "subway",
  "самолёт": "airplane",
  "вертолёт": "helicopter",
  "корабль": "ship",
  "лодка": "boat",
  "катер": "motorboat",
  "яхта": "yacht",
  "паром": "ferry",
  "подводная лодка": "submarine",
  "велосипед": "bicycle",
  "мотоцикл": "motorcycle",
  "мопед": "moped",
  "скутер": "scooter",
  "самокат": "kick scooter",
  "такси": "taxi",
  "грузовик": "truck",
  "фура": "semi-truck",
  "самосвал": "dump truck",
  "экскаватор": "excavator",
  "бульдозер": "bulldozer",
  "трактор": "tractor",
  "скорая помощь": "ambulance",
  "пожарная машина": "fire truck",
  "полицейская машина": "police car",
  "эвакуатор": "tow truck",
  "бензовоз": "fuel truck",
  "микроавтобус": "minibus",
  "внедорожник": "SUV",
  "кабриолет": "convertible",
  "лимузин": "limousine",
  "карт": "go-kart",
  "квадроцикл": "ATV",
  "снегоход": "snowmobile",
  "дирижабль": "airship",
  "воздушный шар": "hot air balloon",
  "дельтаплан": "hang glider",
  "канатная дорога": "cable car",
  "фуникулёр": "funicular",
  "танк": "tank",
  "бронетранспортёр": "armored vehicle",
  "ракета": "rocket",
  "космический корабль": "spaceship",
  "спутник": "satellite",
  "байдарка": "kayak",
  "каноэ": "canoe",
  "катамаран": "catamaran",
  "гидроцикл": "jet ski",
  "электричка": "commuter train",
 // Clothes & Accessories Dictionary
  "одежда": "clothes",
  "футболка": "t-shirt",
  "рубашка": "shirt",
  "блузка": "blouse",
  "свитер": "sweater",
  "кофта": "hoodie",
  "куртка": "jacket",
  "пальто": "coat",
  "плащ": "raincoat",
  "шуба": "fur coat",
  "жилет": "vest",
  "пиджак": "blazer",
  "костюм": "suit",
  "джинсы": "jeans",
  "брюки": "trousers",
  "шорты": "shorts",
  "штаны": "pants",
  "юбка": "skirt",
  "платье": "dress",
  "сарафан": "sundress",
  "комбинезон": "overalls",
  "трусы": "underwear",
  "бюстгальтер": "bra",
  "носки": "socks",
  "гольфы": "knee socks",
  "колготки": "tights",
  "пижама": "pajamas",
  "халат": "robe",
  "купальник": "swimsuit",
  "плавки": "swim trunks",
  "шапка": "hat",
  "кепка": "cap",
  "шляпа": "hat",
  "берет": "beret",
  "шарф": "scarf",
  "перчатки": "gloves",
  "варежки": "mittens",
  "ремень": "belt",
  "галстук": "tie",
  "бабочка": "bow tie",
  "очки": "glasses",
  "солнцезащитные очки": "sunglasses",
  "часы": "watch",
  "браслет": "bracelet",
  "кольцо": "ring",
  "серьги": "earrings",
  "ожерелье": "necklace",
  "цепочка": "chain",
  "кулон": "pendant",
  "брошь": "brooch",
  "заколка": "hair clip",
  "резинка для волос": "hair tie",
  "сумка": "bag",
  "рюкзак": "backpack",
  "кошелёк": "wallet",
  "зонт": "umbrella",
  "обувь": "shoes",
  "кроссовки": "sneakers",
  "ботинки": "boots",
  "туфли": "shoes",
  // Musical Instruments Dictionary
  "гитара": "guitar",
  "электрогитара": "electric guitar",
  "бас-гитара": "bass guitar",
  "акустическая гитара": "acoustic guitar",
  "укулеле": "ukulele",
  "пианино": "piano",
  "рояль": "grand piano",
  "синтезатор": "synthesizer",
  "орган": "organ",
  "аккордеон": "accordion",
  "баян": "button accordion",
  "гармонь": "harmonica",
  "скрипка": "violin",
  "альт": "viola",
  "виолончель": "cello",
  "контрабас": "double bass",
  "арфа": "harp",
  "барабан": "drum",
  "барабаны": "drums",
  "тарелки": "cymbals",
  "тамбурин": "tambourine",
  "маракасы": "maracas",
  "ксилофон": "xylophone",
  "металлофон": "metallophone",
  "колокольчик": "bell",
  "колокол": "bell",
  "треугольник": "triangle",
  "дудка": "pipe",
  "флейта": "flute",
  "саксофон": "saxophone",
  "кларнет": "clarinet",
  "гобой": "oboe",
  "фагот": "bassoon",
  "труба": "trumpet",
  "тромбон": "trombone",
  "валторна": "french horn",
  "туба": "tuba",
  "банджо": "banjo",
  "мандолина": "mandolin",
  "балалайка": "balalaika",
  "домра": "domra",
  "гусли": "gusli",
  "свирель": "pipe",
  "волынка": "bagpipes",
  "губная гармошка": "harmonica",
  "кастаньеты": "castanets",
  "бубен": "tambourine",
  "гонг": "gong",
  "варган": "jaw harp",
  "диджериду": "didgeridoo",
  "терменвокс": "theremin",
  "вибрафон": "vibraphone",
  // Sport & Activities Dictionary
  "футбол": "football",
  "баскетбол": "basketball",
  "волейбол": "volleyball",
  "теннис": "tennis",
  "настольный теннис": "table tennis",
  "бадминтон": "badminton",
  "хоккей": "hockey",
  "фигурное катание": "figure skating",
  "бокс": "boxing",
  "борьба": "wrestling",
  "дзюдо": "judo",
  "карате": "karate",
  "тхэквондо": "taekwondo",
  "фехтование": "fencing",
  "стрельба": "shooting",
  "стрельба из лука": "archery",
  "плавание": "swimming",
  "прыжки в воду": "diving",
  "сёрфинг": "surfing",
  "гребля": "rowing",
  "парусный спорт": "sailing",
  "лыжи": "skiing",
  "сноуборд": "snowboarding",
  "коньки": "ice skating",
  "бобслей": "bobsleigh",
  "биатлон": "biathlon",
  "лёгкая атлетика": "athletics",
  "бег": "running",
  "марафон": "marathon",
  "прыжки в длину": "long jump",
  "прыжки в высоту": "high jump",
  "метание копья": "javelin throw",
  "толкание ядра": "shot put",
  "спортивная гимнастика": "gymnastics",
  "художественная гимнастика": "rhythmic gymnastics",
  "тяжёлая атлетика": "weightlifting",
  "пауэрлифтинг": "powerlifting",
  "кроссфит": "crossfit",
  "йога": "yoga",
  "пилатес": "pilates",
  "велоспорт": "cycling",
  "скейтбординг": "skateboarding",
  "ролики": "roller skating",
  "скалолазание": "rock climbing",
  "альпинизм": "mountaineering",
  "паркур": "parkour",
  "танцы": "dancing",
  "бальные танцы": "ballroom dancing",
  "брейк-данс": "breakdancing",
  "аэробика": "aerobics",
  "фитнес": "fitness",
  "бодибилдинг": "bodybuilding",
  "регби": "rugby",
  "гольф": "golf",
  "крикет": "cricket",
  "бейсбол": "baseball",
  "шахматы": "chess",
  // Household Items Dictionary
  "стол": "table",
  "стул": "chair",
  "кресло": "armchair",
  "диван": "sofa",
  "кровать": "bed",
  "шкаф": "wardrobe",
  "тумбочка": "nightstand",
  "комод": "dresser",
  "полка": "shelf",
  "зеркало": "mirror",
  "картина": "painting",
  "часы": "clock",
  "лампа": "lamp",
  "люстра": "chandelier",
  "телевизор": "television",
  "пульт": "remote control",
  "кондиционер": "air conditioner",
  "обогреватель": "heater",
  "вентилятор": "fan",
  "пылесос": "vacuum cleaner",
  "веник": "broom",
  "швабра": "mop",
  "ведро": "bucket",
  "таз": "basin",
  "утюг": "iron",
  "гладильная доска": "ironing board",
  "стиральная машина": "washing machine",
  "сушилка": "drying rack",
  "прищепка": "clothespin",
  "вешалка": "hanger",
  "подушка": "pillow",
  "одеяло": "blanket",
  "простыня": "sheet",
  "ковёр": "carpet",
  "занавеска": "curtain",
  "скатерть": "tablecloth",
  "салфетка": "napkin",
  "тарелка": "plate",
  "чашка": "cup",
  "стакан": "glass",
  "кружка": "mug",
  "ложка": "spoon",
  "вилка": "fork",
  "нож": "knife",
  "кастрюля": "pot",
  "сковорода": "frying pan",
  "чайник": "kettle",
  "холодильник": "refrigerator",
  "микроволновка": "microwave",
  "плита": "stove",
  "духовка": "oven",
  "тостер": "toaster",
  "блендер": "blender",
  "миксер": "mixer",
  "мультиварка": "slow cooker",
  "разделочная доска": "cutting board",
  "полотенце": "towel",
  "зубная щётка": "toothbrush",
  "расчёска": "comb",
  "фен": "hairdryer",
  // Technology & Gadgets Dictionary
  "телефон": "phone",
  "смартфон": "smartphone",
  "планшет": "tablet",
  "ноутбук": "laptop",
  "компьютер": "computer",
  "монитор": "monitor",
  "клавиатура": "keyboard",
  "мышь": "mouse",
  "принтер": "printer",
  "сканер": "scanner",
  "наушники": "headphones",
  "микрофон": "microphone",
  "колонка": "speaker",
  "камера": "camera",
  "видеокамера": "video camera",
  "проектор": "projector",
  "роутер": "router",
  "модем": "modem",
  "флешка": "flash drive",
  "внешний диск": "external hard drive",
  "карта памяти": "memory card",
  "зарядное устройство": "charger",
  "кабель": "cable",
  "удлинитель": "extension cord",
  "переходник": "adapter",
  "пауэрбанк": "power bank",
  "смарт-часы": "smartwatch",
  "фитнес-браслет": "fitness tracker",
  "беспроводные наушники": "wireless earbuds",
  "колонка блютус": "bluetooth speaker",
  "игровая приставка": "game console",
  "джойстик": "joystick",
  "геймпад": "gamepad",
  "виртуальная реальность": "VR headset",
  "дрон": "drone",
  "квадрокоптер": "quadcopter",
  "3D-принтер": "3D printer",
  "робот-пылесос": "robot vacuum",
  "умная лампа": "smart bulb",
  "умная колонка": "smart speaker",
  "умный замок": "smart lock",
  "термостат": "thermostat",
  "датчик движения": "motion sensor",
  "электронная книга": "e-reader",
  "цифровой фотоаппарат": "digital camera",
  "экшн-камера": "action camera",
  "веб-камера": "webcam",
  "графический планшет": "graphics tablet",
  "стилус": "stylus",
  "клавиатура с подсветкой": "backlit keyboard",
  "игровая мышь": "gaming mouse",
  "коврик для мыши": "mousepad",
  "ноутбучная подставка": "laptop stand",
  "охлаждающая подставка": "cooling pad",
  "USB-хаб": "USB hub",
  "сетевая карта": "network card",
  "ИБП": "UPS",
  "сервер": "server",
  // Weather Dictionary
  "погода": "weather",
  "солнце": "sun",
  "солнечно": "sunny",
  "облако": "cloud",
  "облачно": "cloudy",
  "дождь": "rain",
  "дождливо": "rainy",
  "ливень": "downpour",
  "снег": "snow",
  "снежно": "snowy",
  "град": "hail",
  "ветер": "wind",
  "ветрено": "windy",
  "туман": "fog",
  "туманно": "foggy",
  "гроза": "thunderstorm",
  "молния": "lightning",
  "гром": "thunder",
  "радуга": "rainbow",
  "ураган": "hurricane",
  "торнадо": "tornado",
  "шторм": "storm",
  "метель": "blizzard",
  "пурга": "snowstorm",
  "буря": "tempest",
  "циклон": "cyclone",
  "антициклон": "anticyclone",
  "засуха": "drought",
  "наводнение": "flood",
  "жара": "heat",
  "жара": "hot",
  "тепло": "warm",
  "прохладно": "cool",
  "холод": "cold",
  "холодно": "cold",
  "мороз": "frost",
  "морозно": "frosty",
  "лёд": "ice",
  "гололёд": "black ice",
  "сосулька": "icicle",
  "слякоть": "slush",
  "влажно": "humid",
  "влажность": "humidity",
  "сухо": "dry",
  "роса": "dew",
  "иней": "frost",
  "небо": "sky",
  "ясно": "clear",
  "пасмурно": "overcast",
  "переменная облачность": "partly cloudy",
  // City & Places Dictionary
  "город": "city",
  "деревня": "village",
  "посёлок": "town",
  "столица": "capital",
  "улица": "street",
  "проспект": "avenue",
  "площадь": "square",
  "перекрёсток": "crossroads",
  "светофор": "traffic light",
  "пешеходный переход": "crosswalk",
  "тротуар": "sidewalk",
  "мост": "bridge",
  "набережная": "embankment",
  "парк": "park",
  "сквер": "square",
  "сад": "garden",
  "фонтан": "fountain",
  "памятник": "monument",
  "статуя": "statue",
  "здание": "building",
  "небоскрёб": "skyscraper",
  "дом": "house",
  "квартира": "apartment",
  "подъезд": "entrance",
  "лифт": "elevator",
  "лестница": "stairs",
  "двор": "yard",
  "детская площадка": "playground",
  "остановка": "bus stop",
  "вокзал": "train station",
  "аэропорт": "airport",
  "порт": "port",
  "больница": "hospital",
  "поликлиника": "clinic",
  "аптека": "pharmacy",
  "школа": "school",
  "университет": "university",
  "библиотека": "library",
  "музей": "museum",
  "театр": "theater",
  "кинотеатр": "cinema",
  "цирк": "circus",
  "зоопарк": "zoo",
  "стадион": "stadium",
  "бассейн": "swimming pool",
  "спортзал": "gym",
  "магазин": "store",
  "супермаркет": "supermarket",
  "рынок": "market",
  "торговый центр": "shopping mall",
  "ресторан": "restaurant",
  "кафе": "cafe",
  "бар": "bar",
  "гостиница": "hotel",
  "банк": "bank",
  "банкомат": "ATM",
  "почта": "post office",
  "полиция": "police station",
  "пожарная часть": "fire station",
  "церковь": "church",
  "кладбище": "cemetery",
  "завод": "factory"
};

const emojiMap = {
// Animals Emoji
  "cat": "🐱",
  "dog": "🐶",
  "mouse": "🐭",
  "rat": "🐀",
  "hamster": "🐹",
  "rabbit": "🐰",
  "fox": "🦊",
  "wolf": "🐺",
  "bear": "🐻",
  "tiger": "🐯",
  "lion": "🦁",
  "panther": "🐆",
  "leopard": "🐆",
  "cheetah": "🐆",
  "elephant": "🐘",
  "giraffe": "🦒",
  "zebra": "🦓",
  "horse": "🐴",
  "pony": "🐴",
  "donkey": "🫏",
  "cow": "🐮",
  "bull": "🐂",
  "pig": "🐷",
  "boar": "🐗",
  "sheep": "🐑",
  "ram": "🐏",
  "goat": "🐐",
  "deer": "🦌",
  "moose": "🫎",
  "antelope": "🦌",
  "buffalo": "🐃",
  "hippo": "🦛",
  "rhino": "🦏",
  "monkey": "🐵",
  "gorilla": "🦍",
  "chimpanzee": "🐵",
  "sloth": "🦥",
  "koala": "🐨",
  "kangaroo": "🦘",
  "panda": "🐼",
  "raccoon": "🦝",
  "badger": "🦡",
  "beaver": "🦫",
  "otter": "🦦",
  "squirrel": "🐿️",
  "hedgehog": "🦔",
  "mole": "🐾",
  "bat": "🦇",
  "camel": "🐫",
  "llama": "🦙",
  "alpaca": "🦙",
  "chicken": "🐔",
  "rooster": "🐓",
  "duck": "🦆",
  "goose": "🪿",
  "turkey": "🦃",
  "swan": "🦢",
  "peacock": "🦚",
  "flamingo": "🦩",
  "penguin": "🐧",
  "ostrich": "🪶",
  "sparrow": "🐦",
  "pigeon": "🕊️",
  "crow": "🐦‍⬛",
  "magpie": "🐦",
  "owl": "🦉",
  "eagle": "🦅",
  "hawk": "🦅",
  "falcon": "🦅",
  "parrot": "🦜",
  "canary": "🐤",
  "hummingbird": "🐦",
  "seagull": "🐦",
  "crane": "🪿",
  "stork": "🕊️",
  "fish": "🐟",
  "shark": "🦈",
  "whale": "🐳",
  "dolphin": "🐬",
  "octopus": "🐙",
  "squid": "🦑",
  "crab": "🦀",
  "lobster": "🦞",
  "shrimp": "🦐",
  "starfish": "⭐",
  "jellyfish": "🪼",
  "seahorse": "🐠",
  "eel": "🐍",
  "ray": "🐟",
  "turtle": "🐢",
  "crocodile": "🐊",
  "alligator": "🐊",
  "snake": "🐍",
  "python": "🐍",
  "lizard": "🦎",
  "chameleon": "🦎",
  "iguana": "🦎",
  "frog": "🐸",
  "toad": "🐸",
  "salamander": "🦎",
  "butterfly": "🦋",
  "bee": "🐝",
  "wasp": "🐝",
  "bumblebee": "🐝",
  "ant": "🐜",
  "spider": "🕷️",
  "scorpion": "🦂",
  "cockroach": "🪳",
  "fly": "🪰",
  "mosquito": "🦟",
  "dragonfly": "🪰",
  "grasshopper": "🦗",
  "cricket": "🦗",
  "beetle": "🪲",
  "ladybug": "🐞",
  "caterpillar": "🐛",
  "snail": "🐌",
  "slug": "🐌",
  "worm": "🪱",
  // Professions Emoji
  "doctor": "🧑‍⚕️",
  "teacher": "🧑‍🏫",
  "firefighter": "🧑‍🚒",
  "police officer": "👮",
  "chef": "🧑‍🍳",
  "artist": "🧑‍🎨",
  "musician": "🧑‍🎤",
  "pilot": "🧑‍✈️",
  "programmer": "🧑‍💻",
  "scientist": "🧑‍🔬",
  "construction worker": "👷",
  "engineer": "🧑‍🔧",
  "driver": "🧑‍✈️",
  "nurse": "🧑‍⚕️",
  "pharmacist": "💊",
  "veterinarian": "🐾",
  "dentist": "🦷",
  "psychologist": "🧠",
  "lawyer": "⚖️",
  "judge": "🧑‍⚖️",
  "journalist": "📰",
  "writer": "✍️",
  "actor": "🎭",
  "director": "🎬",
  "photographer": "📷",
  "designer": "🎨",
  "architect": "📐",
  "accountant": "📊",
  "translator": "🌐",
  "diplomat": "🤝",
  "lifeguard": "🛟",
  "detective": "🕵️",
  "surgeon": "🔪",
  "electrician": "💡",
  "plumber": "🔧",
  "mechanic": "🔩",
  "welder": "🔥",
  "farmer": "🧑‍🌾",
  "baker": "🥖",
  "pastry chef": "🎂",
  "butcher": "🥩",
  "hairdresser": "💇",
  "stylist": "👗",
  "makeup artist": "💄",
  "coach": "📋",
  "athlete": "🏃",
  "barista": "☕",
  "waiter": "🍽️",
  "flight attendant": "✈️",
  "secretary": "📞",
  "manager": "💼",
  "entrepreneur": "🚀",
  "military officer": "🪖",
  // Nature & Weather Emoji
  "sun": "☀️",
  "rain": "🌧️",
  "snow": "❄️",
  "wind": "💨",
  "cloud": "☁️",
  "thunderstorm": "⛈️",
  "lightning": "⚡",
  "thunder": "🌩️",
  "hail": "🌨️",
  "fog": "🌫️",
  "rainbow": "🌈",
  "hurricane": "🌀",
  "tornado": "🌪️",
  "drought": "🏜️",
  "flood": "🌊",
  "heat": "🥵",
  "frost": "🥶",
  "ice": "🧊",
  "sky": "🌌",
  "star": "⭐",
  "moon": "🌙",
  "planet": "🪐",
  "earth": "🌍",
  "air": "💨",
  "water": "💧",
  "fire": "🔥",
  "forest": "🌲",
  "tree": "🌳",
  "leaf": "🍃",
  "flower": "🌸",
  "grass": "🌿",
  "bush": "🪴",
  "mountain": "⛰️",
  "hill": "🏔️",
  "valley": "🏞️",
  "field": "🌾",
  "meadow": "🌼",
  "river": "🏞️",
  "lake": "🌊",
  "sea": "🌊",
  "ocean": "🌏",
  "island": "🏝️",
  "peninsula": "🗾",
  "beach": "🏖️",
  "desert": "🏜️",
  "waterfall": "💦",
  "volcano": "🌋",
  "iceberg": "🧊",
  "cave": "🕳️",
  "rock": "🪨",
  "stone": "🪨",
  "sand": "🏝️",
  "mud": "🟤",
  "soil": "🟫",
  "dew": "💧",
  "icicle": "🧊",
  // Transport Emoji
  "car": "🚗",
  "automobile": "🚘",
  "bus": "🚌",
  "trolleybus": "🚎",
  "tram": "🚋",
  "train": "🚂",
  "suburban train": "🚆",
  "subway": "🚇",
  "airplane": "✈️",
  "helicopter": "🚁",
  "ship": "🚢",
  "boat": "⛵",
  "motorboat": "🛥️",
  "yacht": "🛳️",
  "ferry": "⛴️",
  "submarine": "🔱",
  "bicycle": "🚲",
  "motorcycle": "🏍️",
  "moped": "🛵",
  "scooter": "🛴",
  "kick scooter": "🛴",
  "taxi": "🚕",
  "truck": "🚛",
  "semi-truck": "🚚",
  "dump truck": "🛻",
  "excavator": "🚧",
  "bulldozer": "🚜",
  "tractor": "🚜",
  "ambulance": "🚑",
  "fire truck": "🚒",
  "police car": "🚓",
  "tow truck": "🛻",
  "fuel truck": "⛽",
  "minibus": "🚐",
  "SUV": "🚙",
  "convertible": "🏎️",
  "limousine": "🚘",
  "go-kart": "🏎️",
  "ATV": "🛻",
  "snowmobile": "🛷",
  "airship": "🛸",
  "hot air balloon": "🎈",
  "hang glider": "🪂",
  "cable car": "🚡",
  "funicular": "🚞",
  "tank": "🪖",
  "armored vehicle": "🛡️",
  "rocket": "🚀",
  "spaceship": "🛸",
  "satellite": "🛰️",
  "kayak": "🛶",
  "canoe": "🛶",
  "catamaran": "⛵",
  "jet ski": "🛥️",
  "commuter train": "🚆",
  // Clothes & Accessories Emoji
  "clothes": "👗",
  "t-shirt": "👕",
  "shirt": "👔",
  "blouse": "👚",
  "sweater": "🧥",
  "hoodie": "🦺",
  "jacket": "🧥",
  "coat": "🧥",
  "raincoat": "🧥",
  "fur coat": "🧥",
  "vest": "🦺",
  "blazer": "🤵",
  "suit": "🤵",
  "jeans": "👖",
  "trousers": "👖",
  "shorts": "🩳",
  "pants": "👖",
  "skirt": "👗",
  "dress": "👗",
  "sundress": "👗",
  "overalls": "👖",
  "underwear": "🩲",
  "bra": "👙",
  "socks": "🧦",
  "knee socks": "🧦",
  "tights": "🧦",
  "pajamas": "🌙",
  "robe": "👘",
  "swimsuit": "👙",
  "swim trunks": "🩳",
  "hat": "🧢",
  "cap": "🧢",
  "beret": "👒",
  "scarf": "🧣",
  "gloves": "🧤",
  "mittens": "🧤",
  "belt": "🪢",
  "tie": "👔",
  "bow tie": "🎀",
  "glasses": "👓",
  "sunglasses": "🕶️",
  "watch": "⌚",
  "bracelet": "📿",
  "ring": "💍",
  "earrings": "💎",
  "necklace": "📿",
  "chain": "⛓️",
  "pendant": "🔮",
  "brooch": "🧷",
  "hair clip": "📎",
  "hair tie": "🎗️",
  "bag": "👜",
  "backpack": "🎒",
  "wallet": "👛",
  "umbrella": "☂️",
  "shoes": "👞",
  "sneakers": "👟",
  "boots": "🥾",
  "purse": "👝",
  // Musical Instruments Emoji
  "guitar": "🎸",
  "electric guitar": "🎸",
  "bass guitar": "🎸",
  "acoustic guitar": "🎸",
  "ukulele": "🪕",
  "piano": "🎹",
  "grand piano": "🎹",
  "synthesizer": "🎹",
  "organ": "🪗",
  "accordion": "🪗",
  "button accordion": "🪗",
  "harmonica": "🎹",
  "violin": "🎻",
  "viola": "🎻",
  "cello": "🎻",
  "double bass": "🎻",
  "harp": "🎼",
  "drum": "🥁",
  "drums": "🥁",
  "cymbals": "🎶",
  "tambourine": "🥁",
  "maracas": "🎵",
  "xylophone": "🎼",
  "metallophone": "🎹",
  "bell": "🔔",
  "triangle": "🔺",
  "pipe": "🎵",
  "flute": "🎵",
  "saxophone": "🎷",
  "clarinet": "🎵",
  "oboe": "🎵",
  "bassoon": "🎵",
  "trumpet": "🎺",
  "trombone": "🎺",
  "french horn": "📯",
  "tuba": "📯",
  "banjo": "🪕",
  "mandolin": "🪕",
  "balalaika": "🎵",
  "domra": "🎵",
  "gusli": "🎼",
  "bagpipes": "🎵",
  "castanets": "🪇",
  "gong": "🪘",
  "jaw harp": "🎵",
  "didgeridoo": "🪈",
  "theremin": "🎛️",
  "vibraphone": "🎹",
  // Sport & Activities Emoji
  "football": "⚽",
  "basketball": "🏀",
  "volleyball": "🏐",
  "tennis": "🎾",
  "table tennis": "🏓",
  "badminton": "🏸",
  "hockey": "🏒",
  "figure skating": "⛸️",
  "boxing": "🥊",
  "wrestling": "🤼",
  "judo": "🥋",
  "karate": "🥋",
  "taekwondo": "🥋",
  "fencing": "🤺",
  "shooting": "🎯",
  "archery": "🏹",
  "swimming": "🏊",
  "diving": "🤿",
  "surfing": "🏄",
  "rowing": "🚣",
  "sailing": "⛵",
  "skiing": "⛷️",
  "snowboarding": "🏂",
  "ice skating": "⛸️",
  "bobsleigh": "🛷",
  "biathlon": "🎿",
  "athletics": "🏃",
  "running": "🏃",
  "marathon": "🏃",
  "long jump": "📏",
  "high jump": "📐",
  "javelin throw": "🏹",
  "shot put": "💪",
  "gymnastics": "🤸",
  "rhythmic gymnastics": "🤸",
  "weightlifting": "🏋️",
  "powerlifting": "🏋️",
  "crossfit": "🏋️",
  "yoga": "🧘",
  "pilates": "🧘",
  "cycling": "🚴",
  "skateboarding": "🛹",
  "roller skating": "🛼",
  "rock climbing": "🧗",
  "mountaineering": "🧗",
  "parkour": "🏃",
  "dancing": "💃",
  "ballroom dancing": "💃",
  "breakdancing": "🕺",
  "aerobics": "🤸",
  "fitness": "💪",
  "bodybuilding": "💪",
  "rugby": "🏉",
  "golf": "⛳",
  "cricket": "🏏",
  "baseball": "⚾",
  "chess": "♟️",
  // Household Items Emoji
  "table": "🪑",
  "chair": "🪑",
  "armchair": "🛋️",
  "sofa": "🛋️",
  "bed": "🛏️",
  "wardrobe": "🗄️",
  "nightstand": "🛏️",
  "dresser": "🗄️",
  "shelf": "📚",
  "mirror": "🪞",
  "painting": "🖼️",
  "clock": "⏰",
  "lamp": "💡",
  "chandelier": "💡",
  "television": "📺",
  "remote control": "🔘",
  "air conditioner": "🌬️",
  "heater": "🔥",
  "fan": "🪭",
  "vacuum cleaner": "🧹",
  "broom": "🧹",
  "mop": "🧹",
  "bucket": "🪣",
  "basin": "🪣",
  "iron": "👕",
  "ironing board": "👕",
  "washing machine": "🧺",
  "drying rack": "🧺",
  "clothespin": "📎",
  "hanger": "👔",
  "pillow": "🛌",
  "blanket": "🛌",
  "sheet": "🛏️",
  "carpet": "🟫",
  "curtain": "🪟",
  "tablecloth": "🍽️",
  "napkin": "🍽️",
  "plate": "🍽️",
  "cup": "☕",
  "glass": "🥛",
  "mug": "☕",
  "spoon": "🥄",
  "fork": "🍴",
  "knife": "🔪",
  "pot": "🍲",
  "frying pan": "🍳",
  "kettle": "🫖",
  "refrigerator": "🧊",
  "microwave": "📡",
  "stove": "🔥",
  "oven": "🔥",
  "toaster": "🍞",
  "blender": "🥤",
  "mixer": "🥤",
  "slow cooker": "🍲",
  "cutting board": "🔪",
  "towel": "🧻",
  "toothbrush": "🪥",
  "comb": "🪮",
  "hairdryer": "💨",
  // Technology & Gadgets Emoji
  "phone": "📱",
  "smartphone": "📱",
  "tablet": "📱",
  "laptop": "💻",
  "computer": "🖥️",
  "monitor": "🖥️",
  "keyboard": "⌨️",
  "mouse": "🖱️",
  "printer": "🖨️",
  "scanner": "🖨️",
  "headphones": "🎧",
  "microphone": "🎤",
  "speaker": "🔊",
  "camera": "📷",
  "video camera": "📹",
  "projector": "📽️",
  "router": "📡",
  "modem": "📡",
  "flash drive": "💾",
  "external hard drive": "💽",
  "memory card": "💾",
  "charger": "🔌",
  "cable": "🔌",
  "extension cord": "🔌",
  "adapter": "🔌",
  "power bank": "🔋",
  "smartwatch": "⌚",
  "fitness tracker": "⌚",
  "wireless earbuds": "🎧",
  "bluetooth speaker": "🔊",
  "game console": "🎮",
  "joystick": "🕹️",
  "gamepad": "🎮",
  "VR headset": "🥽",
  "drone": "🛸",
  "quadcopter": "🛸",
  "3D printer": "🖨️",
  "robot vacuum": "🤖",
  "smart bulb": "💡",
  "smart speaker": "🔊",
  "smart lock": "🔐",
  "thermostat": "🌡️",
  "motion sensor": "📳",
  "e-reader": "📖",
  "digital camera": "📸",
  "action camera": "📸",
  "webcam": "📹",
  "graphics tablet": "🎨",
  "stylus": "🖊️",
  "backlit keyboard": "⌨️",
  "gaming mouse": "🖱️",
  "mousepad": "🖱️",
  "laptop stand": "💻",
  "cooling pad": "❄️",
  "USB hub": "🔌",
  "network card": "🌐",
  "UPS": "🔋",
  "server": "🗄️",
  // Weather Emoji
  "weather": "🌤️",
  "sun": "☀️",
  "sunny": "☀️",
  "cloud": "☁️",
  "cloudy": "☁️",
  "rain": "🌧️",
  "rainy": "🌧️",
  "downpour": "🌧️",
  "snow": "❄️",
  "snowy": "🌨️",
  "hail": "🌨️",
  "wind": "💨",
  "windy": "💨",
  "fog": "🌫️",
  "foggy": "🌫️",
  "thunderstorm": "⛈️",
  "lightning": "⚡",
  "thunder": "🌩️",
  "rainbow": "🌈",
  "hurricane": "🌀",
  "tornado": "🌪️",
  "storm": "⛈️",
  "blizzard": "🌨️",
  "snowstorm": "🌨️",
  "tempest": "⛈️",
  "cyclone": "🌀",
  "anticyclone": "☀️",
  "drought": "🏜️",
  "flood": "🌊",
  "heat": "🥵",
  "hot": "🥵",
  "warm": "🌡️",
  "cool": "😌",
  "cold": "🥶",
  "frost": "🥶",
  "frosty": "🥶",
  "ice": "🧊",
  "black ice": "🧊",
  "icicle": "🧊",
  "slush": "💧",
  "humid": "💧",
  "humidity": "💧",
  "dry": "🏜️",
  "dew": "💧",
  "sky": "🌌",
  "clear": "🌙",
  "overcast": "☁️",
  "partly cloudy": "⛅",
  // City & Places Emoji
  "city": "🏙️",
  "village": "🏘️",
  "town": "🏘️",
  "capital": "🏛️",
  "street": "🛣️",
  "avenue": "🛣️",
  "square": "⛲",
  "crossroads": "🚦",
  "traffic light": "🚦",
  "crosswalk": "🚸",
  "sidewalk": "🚶",
  "bridge": "🌉",
  "embankment": "🏞️",
  "park": "🏞️",
  "square": "🏙️",
  "garden": "🌳",
  "fountain": "⛲",
  "monument": "🗿",
  "statue": "🗿",
  "building": "🏢",
  "skyscraper": "🏢",
  "house": "🏠",
  "apartment": "🏢",
  "entrance": "🚪",
  "elevator": "🛗",
  "stairs": "🪜",
  "yard": "🏡",
  "playground": "🛝",
  "bus stop": "🚏",
  "train station": "🚉",
  "airport": "✈️",
  "port": "⚓",
  "hospital": "🏥",
  "clinic": "🏥",
  "pharmacy": "💊",
  "school": "🏫",
  "university": "🎓",
  "library": "📚",
  "museum": "🏛️",
  "theater": "🎭",
  "cinema": "🎬",
  "circus": "🎪",
  "zoo": "🦁",
  "stadium": "🏟️",
  "swimming pool": "🏊",
  "gym": "🏋️",
  "store": "🏪",
  "supermarket": "🏪",
  "market": "🛒",
  "shopping mall": "🏬",
  "restaurant": "🍽️",
  "cafe": "☕",
  "bar": "🍺",
  "hotel": "🏨",
  "bank": "🏦",
  "ATM": "🏧",
  "post office": "🏤",
  "police station": "🚔",
  "fire station": "🚒",
  "church": "⛪",
  "cemetery": "🪦",
  "factory": "🏭"
};
